#!/usr/bin/env bash
#
# ############################################################################
# Project: shell (none)
# File...: lib/system
# Created: Thursday, 2023/01/05 - 21:11:59
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2023/01/12 - 21:15:49
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.3.146
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
#!/usr/bin/bash

_xLIB_SYSTEM_=true

use utils

_OS_=$(uname)
_NOTIFY_APP=''
_NOTIFY_ARG=''

# return current OS
System.OS(){
    echo "${_OS_}"
}
sys.os(){ System.OS "$@"; }

# call system notifyer
System.notification(){
    local title="$1" 
    local text="$2" 
    local level="$3";

    echo -e "\nsys.notify: title: $title; text:$text; level:$level\n";
    
    # case sys.os in
    case $(sys.os) in
        Darwin) 
            _NOTIFY_APP="osascript -e"
            _NOTIFY_ARG="\"display notification \\\"<text>\\\" with title \\\"<title>\\\"\""
            _NOTIFY_ARG=$(echo -e $_NOTIFY_ARG | sed "s/<text>/$text/" | sed "s/<title>/$title/")
        ;;
        Linux)  
            _NOTIFY_APP="notify-send"
            _NOTIFY_ARG="\"$title\" \"$text\""
            [ "$level" == "-c" ] && _NOTIFY_ARG+=' -u critical'

        ;;
    esac
    echo -e "\ncmd: $_NOTIFY_APP $_NOTIFY_ARG\n"
    eval "$_NOTIFY_APP $_NOTIFY_ARG"
}
sys.notify(){ System.notification "$@"; }

# write contents on terminal
System.write(){
    echo "$@"
}
sys.write(){ System.write "$@"; }
