#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/_sudo
# Created: Sunday, 2024/12/08 - 19:47:49                                      #
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)                                 #
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Last Modified: Tuesday, 2026/08/18 - 01:38:12
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Version: 0.0.2.10
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Description:                                                                #
#  >                                                                          #
# #############################################################################
# HISTORY:                                                                    #
#

func_name="_sudo"

if ! type "$func_name" &> /dev/null; then
    
    # Function to run a command with sudo
    function _sudo() {
        _cmd_=$1  # Store the command to be run
        # log "running 'sudo $_cmd_ '"; echo  # Print the command being run
        log "running 'sudo $_cmd_ '"
        eval "$_cmd_"  # Evaluate and run the command
    }

else
    xs_debug "xs_source() error! Function's '$func_name' already defined.\n"
fi