#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/append_file
# Created: Sunday, 2025/02/14 - 00:37:39
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/09/13 - 13:21:05
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.4.14
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

func_name="append_file"

if ! type "$func_name" &> /dev/null; then
    
    # def append_file(filename, content)
    function appendFile(){
        local file=$1; shift
        local content="$*"
        local cmd=""
        local content_cmd="echo -e '$content'"
        local tee_cmd="tee -a $file"
        ! check_path "$file" && { tee_cmd="sudo $tee_cmd"; }
        cmd="$content_cmd | $tee_cmd"
        echo -e "\tadding '${content/\\n/}' to '$file'."
        eval "$cmd" >> $APP_LOG 2>&1 || { echo "$project_name install aborted!"; exit 2; } 
    }

    function append_file(){ appendFile "$@"; }

else
    xs_debug "xs_source() error! Function's '$func_name' already defined.\n"
fi