#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/arrays
# Created: Sunday, 2024/12/08 - 04:43:49
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/08/10 - 23:00:29
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.12
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# Função para definir um valor em um array associativo simulado
# array_set name key value
function array_set() {
    local name=$1
    local key=$2
    local value=$3
    eval "${name}_${key}=\"${value}\""
}

# Função para obter um valor de um array associativo simulado
# array_get name key
function array_get() {
    local name=$1
    local key=$2
    eval "echo ${name}_${key}"
}