#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/dots
# Created: Thursday, 2022/12/29 - 23:06:02
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2026/08/18 - 08:48:32
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.14
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

func_name="dots"

if ! type "$func_name" &> /dev/null; then
    # print msg with dots
    dots() {
        local pad=$(printf "%0.1s" "."{1..60})
        printf " * %s%*.*s" "$1" 0 $((60-${#1})) "$pad"
        return 0
    }
    
else
    xs_debug "xs_source() error! Function's '$func_name' already defined.\n"
fi