#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/gen_pass
# Created: Sunday, 2026/09/13 - 22:33:39
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2026/09/17 - 20:37:37
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.34
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#


gen_pass() {
    # --- char groups ---
    local upper='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    local lower='abcdefghijklmnopqrstuvwxyz'
    local digits='0123456789'
    local special_basic='*@$.!\#_-'
    local special_ext='\"~`!@#$%^&*()_+-=[]{}|;:,.<>/?'

    # --- Defaults ---
    local password_size=16
    local use_upper=1 use_lower=1 use_digits=1 use_chars_basic=1 use_chars_extended=0

    # --- args parse ---
    local groups=""
    local arg
    for arg in "$@"; do
        case "$arg" in
            # set groups 
            -u | --upper   ) use_upper=1 ;;
            -l | --lower   ) use_lower=1 ;;
            -d | --digits  ) use_digits=1 ;;
            -b | --basic   ) use_chars_basic=1 ;;
            -e | --ext     ) use_chars_extended=1 ;;
            # unset groups
            -U | --no-upper ) use_upper=0 ;;
            -L | --no-lower ) use_lower=0 ;;
            -D | --no-digits) use_digits=0 ;;
            -B | --no-basic ) use_chars_basic=0 ;;
            -E | --no-ext   ) use_chars_extended=0 ;;
            [0-9]*) password_size="$arg" ;;
            *) echo "Uso: gen_pass [-u] [-l] [-d] [-b] [-e] [--no-X] [tamanho]" >&2; return 1 ;;
        esac
    done

    # no flag?, use default
    if [[ -z "${1:-}" ]]; then
        use_upper=1 use_lower=1 use_digits=1 use_chars_basic=1 use_chars_extended=0
    fi

    # --- get charset ---
    local chars=""
    (( use_upper ))          && chars+="$upper"
    (( use_lower ))          && chars+="$lower"
    (( use_digits ))         && chars+="$digits"
    (( use_chars_basic ))    && chars+="$special_basic"
    (( use_chars_extended )) && chars+="$special_ext"

    # --- password generation ---
    local i gen_pass=""
    for ((i=0; i<password_size; i++)); do
        gen_pass+="${chars:RANDOM%${#chars}:1}"
    done
    printf '%s\n' "$gen_pass"
}


# gen_pass() {
#     local password_size=16
#     local chars='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789*@$.!\#'
#     local gen_pass="" c
#     exec 3</dev/urandom
#     while (( ${#gen_pass} < password_size )); do
#         IFS= read -r -n1 c <&3
#         case "$c" in
#             [a-zA-Z0-9*@$.!\#]) gen_pass+="$c" ;;
#         esac
#     done
#     exec 3<&-
#     echo "$gen_pass"
# }   

# function gen_pass() {
#     local password_size=45
#     local chars='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789*@$.!\#'
#     local gen_pass=""
#     local i
#     for ((i=1; i<=password_size; i++)); do
#         gen_pass+="${chars:RANDOM%${#chars}:1}"
#     done
#     echo "$gen_pass"
# }
