#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/get_git
# Created: Tuesday, 2023/02/25 - 18:50:01
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2026/08/18 - 09:16:40
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.4
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# search and return a git config (local or global)
# getGit user.name author.name
getGit(){
    local git_cmd="git config" _git_config
    for c in "$@" ; do
        _git_config=$($git_cmd "$c")
        [ -n "$_git_config" ] && { echo "$_git_config" ; break; }
        _git_config=$($git_cmd --global "$c")
        [ -n "$_git_config" ] && { echo "$_git_config" ; break; }
    done
}