#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/get_author_info
# Created: ..., 2024/12/09 - 15:26:56
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2026/08/18 - 02:23:07
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.5
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

func_name="get_author_info"

if ! type "$func_name" &> /dev/null; then
    # Function to get author information
    get_author_info() {
        local type=$1
        local config_keys=("user.$type" "author.$type")
        local default_value=$USER
        local fallback='<unknown>'

        for key in "${config_keys[@]}"; do
            local value=$(git config --global "$key")
            if [ -n "$value" ]; then
                echo "$value"
                return
            fi
        done

        if [ -n "$default_value" ]; then
            echo "$default_value"
        else
            echo "$fallback"
        fi
    }

else
    xs_debug "xs_source() error! Function's '$func_name' already defined.\n"
fi