#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/ifname
# Created: Sunday, 2026/08/23 - 22:08:53
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/08/23 - 22:10:33
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.4
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# show aliases (functions)
ifname() {
    local base_index=-1
    local current_index=0

    for ((i=0; i<${#FUNCNAME[@]}; i++)); do
        if [ "${FUNCNAME[i]}" == "main" ] || [ "${FUNCNAME[i]}" == "source" ]; then
            base_index=$i
            break
        fi
    done

    if [ "$base_index" -ne -1 ]; then
        local distance=$((base_index - current_index))
        if [ "$distance" -eq 1 ]; then
            echo "${FUNCNAME[current_index]}"
        else
            local intermediate_index=$((base_index - 1))
            echo "${FUNCNAME[intermediate_index]}"
        fi
    else
        echo "${FUNCNAME[2]}"
    fi
}