#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/rainbow
# Created: Thursday, 2022/12/29 - 23:06:02
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2026/08/18 - 08:38:57
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.13
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

func_name="rainbow"

if ! type "$func_name" &> /dev/null; then
    # prints a table with supported colors
    rainbow(){
        for (( i = 0; i < 8; i++ )); do 
            echo -e "\033[0;3${i}m FG: (0;3$i); \033[1;3${i}m FG-Light: (1;3$i) -> \033[0;4${i}m BG: (0;4$i); \033[1;4${i}m BG-Light: (1;4$i) \033[0m "
        done
    }
    
else
    xs_debug "xs_source() error! Function's '$func_name' already defined.\n"
fi