#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/require_root
# Created: Sunday, 2026/08/09 - 18:05:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/08/16 - 21:42:20
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.2.7
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# function to verify if the current user is root
function requireROOT() {
    local msg=$1
    [ -z "$msg" ] && msg="You need to be ROOT to run this script."
    if [ $UID -ne 0 ]; then
        echo -e "$msg"
        exit 1
    fi
}
function require_root() { requireROOT "$@"; }

function is_root() {
    if [ $UID -eq 0 ]; then
        return 0
    else
        return 1
    fi    
}
