#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/require_root
# Created: Sunday, 2026/08/09 - 18:05:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/09/21 - 17:45:35
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.4.19
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

func_name="require_root"

if ! type "$func_name" &> /dev/null; then

    # function to verify if the current user is root
    function require_root() {
        local msg=$1

        XS_LAST_USER=$(last | head -n1 | awk '{print $1}')

        [ -z "$msg" ] && msg="You need to be ROOT to run this script."
        
        if [ $UID -ne 0 ]; then
            echo -e "$msg"
            exit 1
        fi

        return 0
    }
    function requireROOT() { require_root "$@"; }

    # function to check if current user is ROOT 
    function is_root() {
        if [ $UID -eq 0 ]; then
            return 0
            # echo true 
        else
            return 1
            # echo false
        fi    
    }
    function isROOT?(){ is_root "$@"; }
    
else
    xs_debug "xs_source() error! Function's '$func_name' already defined.\n"
fi