#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/require_root
# Created: Sunday, 2026/08/09 - 18:05:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/08/09 - 18:06:25
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.3
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# function to verify if the current user is root
requireROOT() {
    local msg=$1
    [ -z "$msg" ] && msg="You need to be ROOT to run this script."
    if [ $UID -ne 0 ]; then
        echo -e "$msg"
        exit 1
    fi
}
require_root() { requireROOT "$@"; }