#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/rev
# Created: Monday, 2026/08/24 - 23:42:46
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/08/24 - 23:47:26
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.5
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
# rev alternative

function rev() {
    local input="$*"
    local reversed=""
    local length=${#input}

    for ((i=length-1; i>=0; i--)); do
        reversed="${reversed}${input:i:1}"
    done

    echo "$reversed"
}