#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/ucase
# Created: Sunday, 2026/08/09 - 21:09:56
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/08/09 - 21:10:12
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.1
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

function ucase() {
    local input="$1"
    local output=""
    local char
    for (( i=0; i<${#input}; i++ )); do
        char="${input:i:1}"
        case "$char" in
            [a-z]) 
                # Converte ASCII: subtrai 32 (0x20) do código do caractere
                printf -v char '%b' "\\$(printf '%03o' $(( $(printf '%d' "'$char") - 32 )) )"
                ;;
        esac
        output+="$char"
    done
    printf '%s' "$output"
}