#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/upcase
# Created: Sunday, 2024/12/08 - 19:47:49                                      #
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)                                 #
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Last Modified: Sunday, 2026/08/09 - 15:46:25
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Version: 0.0.1.4
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Description:                                                                #
#  >                                                                          #
# #############################################################################
# HISTORY:                                                                    #
#

# Function to convert a string to uppercase
upcase() {
    echo "$1" | tr '[:lower:]' '[:upper:]'  # Convert the input string to uppercase
}