#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/upcase
# Created: Sunday, 2024/12/08 - 19:47:49                                      #
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)                                 #
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Last Modified: Sunday, 2026/08/16 - 23:52:51
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Version: 0.0.2.7
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~#
# Description:                                                                #
#  >                                                                          #
# #############################################################################
# HISTORY:                                                                    #
#

# Function to convert a string to uppercase
function upcase() {
    echo "$1" | tr '[:lower:]' '[:upper:]'  # Convert the input string to uppercase
}