#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/xs_debug
# Created: Tuesday, 2026/08/11 - 03:28:21
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/08/17 - 01:34:01
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.5.40
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# verify if DEBUG is enabled
is_debug_enabled(){
  if [[ -n "$XSDEBUG" ]] || [[ -n "$D" ]] || [[ -n "$DEBUG" ]]; then
    return 0
  else
    return 1
  fi
}

# show debug message, if its enabled
xs_debug(){
  # define sleep time
  case "${1}" in
    -s | --sleep | -t | --time | --timeout) shift; XS_DEBUG_SLEEP=${2}; shift; ;;
    *) XS_DEBUG_SLEEP=0.3 ;;
  esac
  
  if is_debug_enabled; then
    # echo -e "$@"
    printf "$@"
    sleep $XS_DEBUG_SLEEP 
  fi
}