#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/xs_debug
# Created: Tuesday, 2026/08/11 - 03:28:21
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2026/08/21 - 02:58:43
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.7.94
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# verify if DEBUG is enabled
is_debug_enabled(){
  if [[ -n "$XSDEBUG" ]] || [[ -n "$D" ]] || [[ -n "$DEBUG" ]]; then
    return 0
  else
    return 1
  fi
}

# show debug message, if its enabled
xs_debug(){
  # define sleep time
  case "$1" in
    -s | --sleep ) shift; XS_DEBUG_SLEEP=$1; shift;  ;;
    -d | --detail) shift; XS_DEBUG_DETAILS=1; ;;
    *) XS_DEBUG_SLEEP=0.3; ;;
  esac
  
  if is_debug_enabled; then
    # echo -e "$@"
    printf "$@"
    sleep $XS_DEBUG_SLEEP 
    
    # more details requested?
    if [ -n "$XS_DEBUG_DETAILS" ]; then
      # command: ${BASH_COMMAND[0]}\n\
      echo -e "${RED}\
      === XS_DEBUG_DETAILS ===\n\
      File: ${BASH_SOURCE[0]}\n\
      Function: ${FUNCNAME[0]}\n\
      caller_line: ${BASH_LINENO[0]}\n\
      current_line: ${LINENO}\n\
      \n\
      === stack (require extdebug) ===\n\
      ARGS COUNT: ${BASH_ARGC[0]}\n\
      # BASH_ARGV está em ordem inversa, requer cuidado para imprimir
      ARGS stack: ${BASH_ARGV[@]}\n\
      === END ===\n\
      ${RESET}"
      read
    fi
    
  fi
}