#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/xs_debug
# Created: Tuesday, 2026/08/11 - 03:28:21
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2026/08/27 - 23:06:48
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.8.123
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

if [ -n "$D" ]; then
  XS_DEBUG_LEVEL=$D
else
  [ -z "$XS_DEBUG_LEVEL" ] && export XS_DEBUG_LEVEL=1
fi

# verify if DEBUG is enabled
is_debug_enabled(){
  if [[ -n "$XSDEBUG" ]] || [[ -n "$D" ]] || [[ -n "$DEBUG" ]]; then
    # if [ -n "$D" ]; then
    #   XS_DEBUG_LEVEL=$D
    # else
    #   [ -z "$XS_DEBUG_LEVEL" ] && export XS_DEBUG_LEVEL=1
    # fi
    return 0
  else
    return 1
  fi
}

# show debug message, if its enabled
xs_debug(){
  # define sleep time
  case "$1" in
    -s | --sleep ) shift; XS_DEBUG_SLEEP=$1; shift; ;;
    -d | --detail) shift; XS_DEBUG_DETAILS=1;       ;;
    -l | --level ) shift; XS_DEBUG_NOW=$1;   shift  ;;
    *) 
      XS_DEBUG_SLEEP=0.3
      XS_DEBUG_NOW=1
    ;;
  esac
  
  if is_debug_enabled; then
    
    if [[ "$XS_DEBUG_NOW" -le "$XS_DEBUG_LEVEL" ]]; then
      printf "$@"
      sleep $XS_DEBUG_SLEEP 
    fi
    
    # more details requested?
    if [ -n "$XS_DEBUG_DETAILS" ]; then
      # command: ${BASH_COMMAND[0]}\n\
      echo -e "${RED}\
      === XS_DEBUG_DETAILS ===\n\
      File: ${BASH_SOURCE[0]}\n\
      Function: ${FUNCNAME[0]}\n\
      caller_line: ${BASH_LINENO[0]}\n\
      current_line: ${LINENO}\n\
      \n\
      === stack (require extdebug) ===\n\
      ARGS COUNT: ${BASH_ARGC[0]}\n\
      # BASH_ARGV está em ordem inversa, requer cuidado para imprimir
      ARGS stack: ${BASH_ARGV[@]}\n\
      === END ===\n\
      ${RESET}"
      read
    fi
    
  fi
}