#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/xs_hl
# Created: Tuesday, 2026/08/18 - 12:54:16
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Wednesday, 2026/08/19 - 17:57:55
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.6
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > return 'horizontal line' with current screen size
# ############################################################################
# HISTORY:
#

function xs_hl(){
    xs_require seq tput
    for i in $(seq 1 "$(($(tput cols)-3))"); do echo -n "$1"; done
}