#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/xs_source
# Created: Sunday, 2026/08/09 - 17:55:06
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2026/08/20 - 07:02:35
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.18.332
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

if ! type xs_source &> /dev/null; then

  XS_SOURCE_FILES=''
  XS_SOURCE_BASE_URL="https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master"

  # load debug functions
  if ! type is_debug_enabled &> /dev/null; then
    _xd="$xSHELL_PATH/functions/xs_debug"
    if [ -f "$_xd" ]; then
      source "$_xd"
    else
      source /dev/stdin <<< "$(curl -sSL ${XS_SOURCE_BASE_URL}/functions/xs_debug)"
    fi
    # load colors
    if [ -z "${RED}" ] &> /dev/null; then
      _xc="$xSHELL_PATH/colors"
      if [ -f "$_xc" ]; then
        source "$_xc"
      else
        source /dev/stdin <<< "$(curl -sSL ${XS_SOURCE_BASE_URL}/colors)"
      fi
    fi
    
  fi


  # def xs_source(filename): function to source a script from the repository (local or using curl)
  #   ex: xs_source "args system colors upcase"
  function xs_source() {
    # define how source files will be get
    case "${1}" in
      -b | --both  | --both-allow) shift; XS_SOURCE_FLAG=both  ;;
      -w | --web   | --web-only  ) shift; XS_SOURCE_FLAG=web   ;;
      -l | --local | --local-only) shift; XS_SOURCE_FLAG=local ;;
      *) shift; XS_SOURCE_FLAG=none ;;
    esac

    # debug header
    xs_debug "${REVERSE} $0 ${RESET} - ${YELLOW}xs_source ${RESET} (FLAG: ${XS_SOURCE_FLAG}) '${CYAN}$*${RESET}'\n"
    
    # store functions loaded by xs_source among multiple calls 
    [ -z "$XS_SOURCE_FILES" ] && XS_SOURCE_FILES+=$@ || XS_SOURCE_FILES+=" $@"

    # iterate over all libs/functions
    for filename in "$@"; do

      if ! type $filename &> /dev/null; then

        # test if local filename exist?
        success=false

        if [ "$XS_SOURCE_FLAG" == "local" ] || [ "$XS_SOURCE_FLAG" == "both" ] || [ "$XS_SOURCE_FLAG" == "none" ]; then
        
          # for f in "$filename" "./$filename" "./lib/$filename" "./vendor/$filename" "../$filename" "$APP_DIR/$filename " "$xSHELL_PATH/$filename"; do
          for f in "$xSHELL_PATH/$filename" "$xSHELL_PATH/functions/$filename"; do
            
            if source "${f}" &> /dev/null; then
              xs_debug " \`-> ${YELLOW}xs_source${RESET} ${CYAN}%-45s${RESET} ${GREEN}%15s${RESET}\n" $f "[success] (local)"
              success=true
              break
            # else
            #   xs_debug " \`-> ${YELLOW}xs_source${RESET} ${CYAN}$f${RESET} - ${RED}Error - local${RESET}"
            #   [ -f "$f" ] && xs_debug "$f exists but not loaded. (end of line CRLF should be LF)"
            fi
              
          done
          
        fi
        
        # not found yet? try to load from web respository  
        if [ $success == "false" ]; then
          
          # can source from web?
          if [ "$XS_SOURCE_FLAG" == "web" ] || [ "$XS_SOURCE_FLAG" == "both" ]; then
            
            for f in "${XS_SOURCE_BASE_URL}/${filename}" "${XS_SOURCE_BASE_URL}/functions/${filename}"; do

                if source /dev/stdin <<< "$(curl -sSL ${f}) &>/dev/null"; then
                  xs_debug " \`-> ${YELLOW}xs_source${RESET} ${CYAN}%-65s${RESET} ${GREEN}%15s${RESET}\n" $f "[success] (web)"

                  success=true
                  break
                fi
                
            done
            
            [ "$success" == "false" ] && xs_debug " \`-> ${YELLOW}xs_source${RESET} ${CYAN}$filename${RESET} - ${RED}Error - web${RESET}\n" >&2 && exit 1
          fi
        fi

      # type $filename true? this function is defined. 
      else
        xs_debug "${YELLOW} !!! xs_source - function already defined! ${CYAN}%-17s${RESET} ${YELLOW}%15s${RESET}\n" $filename "[ignore] (unknown)"
      fi

    done
  }

  function xsource(){ xs_source "$@"; }
  function xs_func(){ xs_source "$@"; }
  function xs_def(){ xs_source "$@"; }

else
  xs_debug "Error! Function 'xs_source' already defined.\n"
fi