#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: functions/xs_source
# Created: Sunday, 2026/08/09 - 17:55:06
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/08/09 - 20:59:45
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.16
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# def xs_source(name): function to source a script from the repository (local or using curl)
#   ex: xs_source "init colors functions/upcase"
function xs_source() {
  # iterate over all libs/functions
  for path in "$@"; do
    # test if local path/file exist?
    if [ -f "$path" ]; then
      if ! source "../$path"; then
        echo "xs_source() - Error sourcing local file: $path" >&2
      fi
    else
      # not found? load it from web
      if ! source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master/${path})"; then
        echo "xs_source() - Error sourcing web file: $path" >&2
      fi
    fi
  done
}