#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: args
# Created: Friday, 2022/02/11 - 20:09:07
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/08/24 - 00:45:56
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.2.43.2202
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

_xLIB_ARGS_=true;

use hashs system utils

# update text used in function 'xs_usage'
    # @param $1 -> string to customize each text of help sections. Use this pattern:
        # -<option>="<text>"
    # <options> identify a section and it can be:
        # -h or --header
        # -p or --param
        # -b or --body
        # -f or --footer
# "<text>" is the string associated to this section and is required to be inside ""
xs_help(){
    # loop all params
    for param in "$@"; do
        # split key and value
        key=$(echo "$param" | cut -d '=' -f1)
        val=$(echo "$param" | cut -d '=' -f2)
        
        # check key arg
        case $key in
            -p|--param ) 
                    param_id="$(echo "$val" | cut -d '+' -f1)"; 
                    param_text="$(echo "$val" | cut -d '+' -f2-3)";
                    Hash.put "$args_hash" "$param_id" "$param_text";;
                    
            -b|--body   ) __HELP_BODY__+="$val" ;;
            -h|--header ) __HELP_HEADER__+="\n$val\n" ;;
            -f|--footer ) __HELP_FOOTER__+="$val" ;;
            --long-usage) __HELP_SHOW_ARGS__=true ;;
        esac
    done

    __HELP_USAGE__="usage: \n  ${GREEN}$APP${RESET} "
    if [ $(Hash.count "$args_hash") -le 10 ] || [ -n "$__HELP_SHOW_ARGS__" ]; then
        __HELP_USAGE__+="$(
            Hash.keys "$args_hash" | \
            sed 's/,--.[a-z,-]*//g' | \
            sed 's/,.[a-z,-]*//g' | \
            sed 's/^/[/g' | \
            sed 's/$/]/g' | \
            tr -s '\n' ' '
        )" 

        if [ -n "$RED" ]; then 
            # apply colors
            __HELP_USAGE__=${__HELP_USAGE__//-/${MAGENTA}-}
            __HELP_USAGE__=${__HELP_USAGE__//</${YELLOW}<}
            __HELP_USAGE__=${__HELP_USAGE__//\]/${RESET}\]}
            
            # TODO: optional arguments highlighting
            __HELP_USAGE__=${__HELP_USAGE__//'{'/${YELLOW}'{'}
        fi
    else
        __HELP_USAGE__+="[OPTIONS] "
    fi
}

# show usage information/help
# usage: xs_usage <options>
# `-> <options> can be:
#  -f|--field-error <field_name>  : raise error when a field is empty
#  -m|--missing-param <param_name> : raise error when a required param is missing
#  -r|--reject-unknow <option>     : raise error when a unknow option is used
#  -c|--custom <text>              : custom text to show on usage
#  -h|--help                     : show help message
#  -v|--version                  : show version of this script
xs_usage(){
    # Function to format help options with standard spacing on Darwin systems
    help_options_darwin() {
        local max_length=0
        local options=()

        # Find the maximum length of the options
        while IFS= read -r line; do
            # Extract the option key (first word) from the line
            local option=$(echo "$line" | cut -d ':' -f 1)
            # Determine the length of the option key
            local length=${#option}
            # Update the maximum length if the current option key is longer
            if [ $length -gt $max_length ]; then
                max_length=$length
            fi
            # Add the entire line to the options array
            options+=("$line")
        done <<< "$(Hash.all "$args_hash")"

        # Format the options with standard spacing
        for option in "${options[@]}"; do
            
            # grouping itens
            group=$(echo "$option" | cut -d '+' -f2-9)
            # set default value (if none is configured)
            [ -z "$group" ] && group="Available Options"
            # update if this option has a new group
            if [ "$group" != "$last_group" ]; then
                printf "${BLUE} \`-> %s ${RESET}\n" "$group"
                last_group=$group
            fi
            
            # Extract the option key (first word) from the option
            local key=$(echo "$option" | cut -d ':' -f 1)
            key=${key/\:/ }
            # Extract the description (remaining words) from the option
            local desc=$(echo "$option" | cut -d ':' -f 2-)
            desc=$(echo "$desc" | cut -d '+' -f1)
            # Print the option key and description with standard spacing
            printf "     %-${max_length}s   %s\n" "$key" "$desc"
        done
    }

    # Function to format help options with standard spacing on Linux systems
    help_options_linux(){
        for h in $(
            Hash.all "$args_hash" |      # get all hashes \
            sed "s/:/:/g" |             # add blue color to options description':'\
            sed "s/^-/:-/g" |           # add color to options/flags \
            sed 's/ /./g'               # replace ' ' with '.'  
        ); do
            b=$(echo -e $h | cut -d '+' -f2)
            # echo "'$b' - '$block'"
            if [ -n "${b// }" ]; then 
                [ "${b}" != "${block// /.}" ] && block="${b}" \
                    && __HELP_OPTIONS_DESCRIPTION__+="\n${BLUE}->:$block;${RESET}\n"
                # echo
            else 
                if [ -z "$outblock" ];then
                    block="Available.Options" && __HELP_OPTIONS_DESCRIPTION__+="\n${BLUE}->:$block;${RESET}\n"
                    outblock=true
                fi
                # [ -z "$block" ] && block="Available options" && __HELP_OPTIONS_DESCRIPTION__+="\n->:$block;\n"
            fi
            __HELP_OPTIONS_DESCRIPTION__+="$(echo -e ${h//./ } | cut -d '+' -f1)\n" 

            # apply colors
            if [ -n "$RED" ]; then 
                # arguments description highlighting
                __HELP_OPTIONS_DESCRIPTION__=${__HELP_OPTIONS_DESCRIPTION__//\:/${BLUE}\:}
                # flags highlighting
                __HELP_OPTIONS_DESCRIPTION__=${__HELP_OPTIONS_DESCRIPTION__//-/${MAGENTA}-}
                # block highlighting
                __HELP_OPTIONS_DESCRIPTION__=${__HELP_OPTIONS_DESCRIPTION__//->/${BLUE}->}
                # required arguments highlighting
                __HELP_OPTIONS_DESCRIPTION__=${__HELP_OPTIONS_DESCRIPTION__//</${YELLOW}<}
                # required arguments closing 
                __HELP_OPTIONS_DESCRIPTION__=${__HELP_OPTIONS_DESCRIPTION__//>/>${BLUE}}

                # TODO: optional arguments highlighting
                __HELP_OPTIONS_DESCRIPTION__=${__HELP_OPTIONS_DESCRIPTION__//"{"/"${YELLOW}{"}
            fi
        done

        __HELP_OPTIONS_DESCRIPTION__=$(echo "${__HELP_OPTIONS_DESCRIPTION__//./ }" | \
            awkColumn "-s=:" | \
            sed "s/;/:/g" | \
            sed 's/,/,  /g' )
    }
    
    # generate default help text if user not difined one
    [ -z "$__HELP_USAGE__" ] && xs_help --long-usage
    [ -n "$_XS_ARGS_DEBUG" ] && xs_run_debug "${xRUN_ARGS[@]}"
    
    case "$1" in
        -f|--field-error)
            xs_help --long-usage
            # remove header info on this error msg
            __HELP_HEADER__=''
            __exit_code=3 
            __usage_msg="${RED}Error!${RESET} empty value for ${YELLOW}'$2'${RESET} argument.${RESET}\n\n" 
        ;;

        -m|--missing-param)
            xs_help --long-usage
            # remove header info on this error msg
            __HELP_HEADER__=''
            __exit_code=1 
            __usage_msg="${RED}Error!${RESET} Missing required argument.${RESET}\n\n" 
        ;;
        -r|--reject-unknow)
            xs_help --long-usage
            # remove header info on this error msg
            __HELP_HEADER__=''
            __usage_msg="${RED}Error!${RESET} invalid option ${YELLOW}($2)${RESET}.${RESET}\n\n" 
        ;;
        -c|--custom)
            xs_help --long-usage
            __exit_code=4        
            __usage_msg="$2\n\n" 
        ;;
        -h|--help)
            xs_help
            __usage_full=true
        ;;
        -v|--version)
            echo "$XS_CURRENT_VERSION"; exit
        ;;
        *) 
            __exit_code=0      
            __usage_msg="" 
        ;;
    esac

    # print debug info
    # [ -n "$_XS_ARGS_DEBUG" ] && xs_run_debug  "${xRUN_ARGS[@]}" ;
    
    # prints initial help text
    echo -e "${__HELP_HEADER__}\n${__usage_msg}${__HELP_USAGE__}"

    if [ -n "$__usage_full" ]; then
        # help body text (before params/args)
        [ -n "$__HELP_BODY__" ] && echo -e "\n${__HELP_BODY__}" 
        # [ -z "$block" ] && echo -e "Available options:" || echo -e "$block"
        
        # get all key/values from main hash
        #     pairs stored as 'key:value'. We parse to ':key:value' 
        #       --> sed to add ':' in begin of each line 
        #       --> column to equaly expand texts
        # Hash.all "$args_hash" | sed 's/^-/:-/g' | sed 's/,/,:/' | column -t -s ':'

        # case sys.os in
        case $(xsys.os) in
            # Darwin) __HELP_OPTIONS_DESCRIPTION__="\n$(help_options_darwin)\n" ;;
            # Linux ) help_options_linux ;;
            *) __HELP_OPTIONS_DESCRIPTION__="\n$(help_options_darwin)\n" ;;
        esac

        echo -e "${__HELP_OPTIONS_DESCRIPTION__}${RESET}"
        
        # not null? prints footer 
        [ -n "$__HELP_FOOTER__" ] && echo -e "${__HELP_FOOTER__}\n" 
        echo -e "${GREEN}v${XS_CURRENT_VERSION}${RESET} on ${YELLOW}${XS_UPDATED_AT}${RESET} - writen by ${BOLD}${CYAN}${XS_AUTHOR_NAME}${RESET}"
    
    else
        echo -e ""
    fi
    # quit with error code
    exit $__exit_code
}

# xarg: id="-h,--help" var=variable:value
    #   --> dynamic create ARGs/actions
    # @param $1: ARGs keys. Use comma (,) to separete multiple keys to same action
    #   --> id="-h,--help"
    # @param $2: action to execute with keys
    #   this can be: [code] or [var]
    #   --> code="cmd1; cmd2;"
    #       run custom commands (cmd1 ; cmd2)
    #   --> var=myVar1:value
    #       create a var named 'myVar1' and assign 'value'
    #       * var=myVar1+r
    #       create a var 'myVar1' and require another param as value. If next arg was empyt raise a error.
    # @param $3: description to generate help for this arg/action
#   --> desc="text" 
xarg(){
    
    xs_func ifname
    xs_debug "${REVERSE} ${BASH_SOURCE[1]} - call of $(ifname)() '$*' ${RESET}\n"
    
    #TODO: refactor code below
    while [ "$1" != "" ]; do
        case $1 in
            # planning a new feature
            # --value)
            #     # echo ''
            #     method=value
            #     value=$2

            # ;;
            -i| --id) 
                key=$1; shift
                option_key=$(echo "$1" | tr -s ',' '|')
                option_default=$1
                description=''

                # autocreate xarg variable with short flag letter
                # Ex: xarg function with -s param will generate variable xarg=s
                method=var
                action_vars=''
                var_name=xarg
                var_value=$(echo $option_key | cut -d '|' -f1 | cut -d '-' -f2)
                assign_vars=" $var_name+=\"$var_value\" "
                # [ -n "$action_vars" ] && action_vars+=" ; "
                action_vars+=" $assign_vars  "
                option_rule=''
                desc_var=""
            ;;
            -v|--var) 
                key=$1; shift
                method=var
                # action_vars=''
                var_name=''
                var_value=''
                option_rule=""
                
                # $1 content -> can be a list of values comma separated
                    # value,value
                
                for v in ${1//,/ }; do
                    
                    # method used in this arg
                    option_content=$v

                    var_name="$(echo "$option_content" | cut -d ':' -f1 | cut -d '+' -f1  )"

                    case "$option_content" in
                       *:* ) 
                            # ":" will directly set value to variable
                                #  variable:value
                            
                            var_value="$(echo "$option_content" | cut -d ':' -f2 | cut -d '+' -f1)"
                            assign_vars=" $var_name=\"$var_value\" "
                            # clear rules
                            option_rule=""
                            var_value=''
                        ;;
                       *+* ) 
                            # "+" will require a new arg in command line. this value will be set to variable
                                # variable+r 
                            
                            current_rule="$(echo "$option_content" | cut -d '+' -f2)"

                            case "$current_rule" in
                                # 'r' means 'required'
                                r)  
                                    option_rule+=" shift; .xs --require-value \"\$1\" \"$var_name\" ;" 
                                    desc_var+=" <$var_name>" 
                                    if [ -z "$var_value" ]; then
                                        assign_vars=" $var_name=\"\$1\" "
                                    fi

                                ;;
                                # 'o' for 'optional'
                                o)  
                                    option_rule+=" " 
                                    desc_var+=" {$var_name}" 
                                    if [ -z "$var_value" ]; then
                                        assign_vars=" [ -n \"\$2\" ] && { shift ; $var_name=\"\$1\" ;  } "
                                    fi
                                ;;
                            esac
                       ;;
                    esac
                    [ -n "$action_vars" ] && action_vars+=" ; "
                    action_vars+=" $option_rule $assign_vars  "
                    # fix priblem when require two vars
                    # ex --var v1+r,v2+r
                    option_rule=''
                done
                
            ;;
            -c|--code) 
                key=$1; shift
                method=code
                option_content=$1 
                desc_var=''

            ;;
            -d|--desc) 
                key=$1; shift
                description="$1" 
            ;;
            # FIXME: --block not working on Darwin system
            -b|--block|-g|--group|-s|--section)
                method=block
                block="$2"
            ;;
            -n|--longflag-nodash)
                method=longflags
                _xARGS_NO_DAHS=true
            ;;
            -h|--header)
                method=header
                .xs --require-value "$1" "$2"
                xs_help --header="$2"
            ;;
            -f|--footer)
                method=footer
                .xs --require-value "$1" "$2"
                xs_help --footer="$2"
            ;;
            --no-help)
                no_help=true;
                block=none
                method=none
                key=none
            ;;
            --no-version)
                no_version=true
                block=none
                method=none
                key=none
            ;;
        esac
        shift
    done

    # bypass when no arguments has been defined
    if [ "$method" != "block" ] && [ "$method" != "longflags" ] && [ "$method" != "footer" ] && [ "$method" != "header" ]; then
        xs_help --param="${option_default}${desc_var}+${description}+${block}"
    fi

    # generate output
    case $method in
        var ) __RUN_ARGS_CASE_OPTIONS__+=" $option_key) $action_vars    ;; \n" ;;
        code) __RUN_ARGS_CASE_OPTIONS__+=" $option_key) $option_content ;; \n" ;;
        # --reject-unknow) __RUN_ARGS_CASE_OPTIONS__+="*) xs_usage -r \$1 ;; \n" ;;
    esac
}

# xrun "$@"
# generates a loop with case struct to evaluate all ARGs defined using `xarg`
xrun(){
    
    xs_func ifname
    xs_debug "${REVERSE} ${BASH_SOURCE[1]} - call of $(ifname)() '$*' ${RESET}\n"
    xRUN_ARGS="$@"

    xs_run_help(){
        echo -e "${GREEN}${UNDERLINE}'lib/args'${RESET} "$args_hash" functions (${YELLOW}xarg${RESET}, ${YELLOW}xrun${RESET})
        \n${YELLOW}1) xarg${RESET} -> set args to be validate in 'xrun' function
        \nusage: ${YELLOW}xarg ${CYAN}[OPTION] ${MAGENTA}<VALUE>${RESET}\
        \n\nAvailable options:\
        "
        echo "\
        \n${CYAN} -i, --id   ${MAGENTA} <VALUE>${RESET}; short and long key. ex: '-h,--help'\
        \n${CYAN} -c, --code ${MAGENTA} <VALUE>${RESET}; shell code to run by 'eval'\
        \n${CYAN} -v, --var  ${MAGENTA} <VALUE>${RESET}; define vars\
        \n${CYAN} -d, --desc ${MAGENTA} <TEXT> ${RESET}; description to this 'arg'\
        \n\n # Grouping options #\n
        \n${CYAN}  -b, --block   ${MAGENTA}<VALUE>${RESET} or\
        \n${CYAN}  -g, --group   ${MAGENTA}<VALUE>${RESET} or\
        \n${CYAN}  -s, --section ${MAGENTA}<VALUE>${RESET} or\
        \
        " | awkColumn "-s=;"
        # " | column -t -s ';'
        
        echo -e "\
        \nExamples:\
        \n  ${YELLOW}xarg ${CYAN}--id -h,--help ${MAGENTA}--code 'xs_usage --help'  ${CYAN}--desc ${MAGENTA}'run function \"xs_usage\"'${RESET}\
        \n  ${YELLOW}xarg ${CYAN}--id -v,--var  ${MAGENTA}--var  var:value,url+r  ${CYAN}--desc ${MAGENTA}'equivalent to \"var=value; read url\"'${RESET}\
        \n  ${YELLOW}xarg ${CYAN}--block ${MAGENTA}'new block'${RESET}\
        
        \n${YELLOW}2) xrun${RESET} -> create 'case struct/validate args' defined via 'function xarg' for your application\
        \n\nusage: ${YELLOW}xrun ${CYAN}[OPTIONS] ${MAGENTA}\"\$@\"${RESET}\
        \n\nAvailable options:\
        "
        
        echo "\
        \n  ${CYAN}--xapp-data${RESET};create default directory for \$APP data ($HOME/.xshell/$APP)\
        \n  ${CYAN}--xrequire-one${RESET};script will require at least one argument\
        \n  ${CYAN}--xreject-unknown${RESET};raise an error if your script receives args not defined\
        \n  ${CYAN}--xversionrc${RESET};use full version with rc (release candidate)
        \n  ${CYAN}--xcolors${RESET};enable color support\
        \n  ${CYAN}--xlib-dirs${RESET};show dirs where xshell lib search for LIBs\
        \n  ${CYAN}--xrequirements${RESET};show requirements report\
        \n  ${CYAN}--xdebug${RESET};prints generated case with args for inspection\
        \n  ${CYAN}--xs_help${RESET};prints this message
        " |  awkColumn "-s=;" 
        # " |  awkColumn "-t=;"
        # " | awk '{ printf "%-8s", $1 } NR % 2 == 0 { printf "\n" }'  
        # " | awk '{ getline line; printf "%s\t%s\n", $0, line }'
        # " | awk -vOFS='\t' 'NF > 0 { $1 = $1 } 1'
        # " > awkColumn -t=;
        # " | column -t -s ';' 

        # echo -e "\n[!] ATENTION:\
        #     \n    1-You can't use 'xrun' arguments in your application.\
        #     \n    2-You must pass all of your app/script args to 'xrun' validate then.\
        #     \n\tex: xrun --xrequire-one \"\$@\"\
        #     \n    3-xrun args will be removed via shift; so they need to be before incoming args (\"\$@\")\
        #     "
        exit 0
    }
    
    xs_run_debug(){
            # \n\$BASH_COMMAND: ${REVERSE} '${BASH_COMMAND[@]}' ${RESET}\
        echo -e "${RED}$(.xs --hl '-')\n# xSHELL DEBUG - begin\
            \n$(.xs --hl '-')${RESET}\n${YELLOW}# 1. variables:${RESET}\n\
            \n\$BASH_SOURCE: ${REVERSE} '$BASH_SOURCE' ${RESET}\
            \n\$DIRSTACK: ${REVERSE} '$DIRSTACK' ${RESET}\
            \n\$FUNCNAME: ${REVERSE} '${FUNCNAME[@]}' ${RESET}\
            
            \n\$xSHELL_PATH: ${REVERSE} '$xSHELL_PATH' ${RESET}\
            
            \n\$xSHELL_LIBS: ${REVERSE} '$(echo -n "${xSHELL_LIBS[@]/$xSHELL_PATH\/}")' ${RESET}\
            \n\$xSHELL_LIBS - count: ${REVERSE} ${#xSHELL_LIBS[@]} ${RESET}\
            
            \n\$xSHELL_DIRS: ${REVERSE} '$(echo -n "${xSHELL_DIRS[@]}")' ${RESET}\
            \n\$xSHELL_DIRS - count: ${REVERSE} ${#xSHELL_DIRS[@]} ${RESET}\

            \n\$XS_SOURCE_FLAG.: ${REVERSE} '$XS_SOURCE_FLAG' ${RESET}\
            \n\$XS_SOURCE_FILES: ${REVERSE} '$XS_SOURCE_FILES' ${RESET}\

            \n\$APP or \$APP_NAME: ${REVERSE} '$APP' ${RESET}\
            \n\$XS_REQUIREMENTS: ${REVERSE} '$XS_REQUIREMENTS' ${RESET}\
            \n\$XS_MISSING_REQUIREMENTS: ${REVERSE} '$XS_MISSING_REQUIREMENTS' ${RESET}\
            
            \n\$APP_PATH: ${REVERSE} '$APP_PATH' ${RESET}\
            \n\$APP_DIR.: ${REVERSE} '$APP_DIR' ${RESET}\
            \n\$APP_HOME: ${REVERSE} '$APP_HOME' ${RESET}\
            \n\$APP_DATA: ${REVERSE} '$APP_DATA' ${RESET}\
            \n\$APP_LOG.: ${REVERSE} '$APP_LOG' ${RESET}\

            \n\$@: ${REVERSE} '${XS_ARGS[*]}' ${RESET}\
            \n\$XS_PARAMS: ${REVERSE} '${XS_PARAMS[*]}' ${RESET}\
            \n\$xarg: ${REVERSE} '$xarg' ${RESET}\

            \n\$XS_AUTHOR_NAME: ${REVERSE} '$XS_AUTHOR_NAME' ${RESET}\
            \n\$XS_AUTHOR_MAIL: ${REVERSE} '$XS_AUTHOR_MAIL' ${RESET}\
            \n\$XS_CREATED_AT.: ${REVERSE} '$XS_CREATED_AT' ${RESET}\
            \n\$XS_UPDATED_AT.: ${REVERSE} '$XS_UPDATED_AT' ${RESET}\
            \n\$XS_VERSION: ${REVERSE} '$XS_VERSION' ${RESET}\
            \n\$XS_VERSION_RC: ${REVERSE} '$XS_VERSION_RC' ${RESET}\
            \n$(.xs --hl '-')\n${YELLOW}# 2. xarg function:${RESET}\n\
            \n$(Hash.all "$args_hash" | cut -d '+' -f1 | column -s : -t)\
            \n$(.xs --hl '-')\n${YELLOW}# 3. xrun function:${RESET}\n\
            \n\$@: ${REVERSE} '${xRUN_ARGS}' ${RESET}\
            \n\$APP_ARGS: ${REVERSE} '${XS_PARAMS[*]}' ${RESET}\n\
            \nwhile [ \$1 != \"\" ]; do\
            \n$__runARGS_case_\
            \nshift\
            \ndone\
            \n${RED}$(.xs --hl -)\n# xSHELL DEBUG - end\
            \n$(.xs --hl -)${RESET}";
    }
    
    xs_generate_case(){
         # fill case with options (xarg)
        __runARGS_case_='case $1 in \n'
        __runARGS_case_+=$__RUN_ARGS_CASE_OPTIONS__
        __runARGS_case_+='esac'
        # apply escape codes (\n \t) when print
        __runARGS_case_=$(echo -e $__runARGS_case_)
        
        [ -n "$_XS_ARGS_REQUIRED" ] && .xs --require-one "$@" && unset _XS_ARGS_REQUIRED;

        # loop all params 
        while [ "$1" != "" ]; do
            # run generated 'case' code
            eval "$__runARGS_case_"
            shift
        done
    }

    # Function to handle joint short flags
    handle_joint_short_flags() {
        local joint_flags="$1"  # The joint short flags passed as an argument
        local length=${#joint_flags}  # The length of the joint short flags string

        # Iterate over each character in the joint short flags string
        for (( i=0; i<length; i++ )); do
            local flag="${joint_flags:i:1}"  # Extract the current character (flag)
            XS_PARAMS+=("-$flag")  # Add the individual flag to the XS_PARAMS array
        done
    }
    
    # set default grouping (has more than zero entries with groups? user defined)
    if [ "$(Hash.all | grep -Ei '\+[a-z]' | wc -l)" -gt 0 ]; then
        # create this group for --help and --version options
        xarg --block "Information Options"
    else
        # no user group? use this for all options
        xarg --block "Available Options"
    fi
    # set default args for any script
    XS_CURRENT_VERSION=$XS_VERSION

    # add support to logflags without '--' prefix
    if [ -z "$_xARGS_NO_DAHS"  ]; then 
        _arg_prefix_="--"
    fi

    # gen default help argument
    if [ -z "$no_help" ]; then
        xarg --id "-h,${_arg_prefix_}help"    \
            --code "xarg+=h ; xs_usage --help" \
            --desc "show this help"
            #  --code "formatHelpOptions" \
    fi

    if [ -z "$no_version" ]; then
        # gen default version argument
        xarg --id "-v,${_arg_prefix_}version" \
            --code "xarg+=v ; xs_usage --version" \
            --desc "print version and exit"
    fi
    
    # store arguments/params to be passed to the script
    XS_PARAMS=()
    
    # search for xrun args 
    while [ "$1" != "" ]; do
        # function to force script to receive at last one param/arg
        case "$1" in
            --xapp-data | --xs-app-home)
                shift; xs_create_app_home
            ;;
            --xrequire-one | --xrequire_one | --require-one | --notNull | --not-null)  
                shift; _XS_ARGS_REQUIRED=true
            ;;
            --xreject-unknown | --reject-unknow | --xreject-unknow)
                shift
                __RUN_ARGS_CASE_OPTIONS__+="*) xs_usage --reject-unknow \$1 ;; \n"
            ;;
            --xversion-full | --xversionrc)
                shift; XS_CURRENT_VERSION=$XS_VERSION_RC
            ;;
            --xdebug | --xsdebug) 
                shift; _XS_ARGS_DEBUG=true; 
            ;;
            --xcolors)
                shift; use colors;
            ;;
            --xscolors | --xs-show-colors | --xs-show-colors) 
                shift; xs_show_colors; exit 0;
            ;;
            --xhelp | --xs-help)
                use utils
                [ -z "$RED" ] && use colors
                local _help_viewer=$(xsys.path bat less more cat)
                shift; xs_run_help | $_help_viewer
            ;;
            --xlib-dirs | --xlibs)
                shift;
                [ -z "$RED" ] && use colors
                echo -e "\n${YELLOW}xSHELL LIB directories:${RESET}\n"
                for dir in "${xSHELL_DIRS[@]}"; do
                    echo -e "${GREEN}  \`-> '${dir}${RESET})"
                done
                echo
                exit
            ;;
            --xsrequirements | --xrequirements)
                shift; xs_requirements_report --colors $_REQUIREMENTS_; exit 0;
            ;;
            *)
                XS_PARAMS+=("$1")
                shift
        esac
    done
    
    # Save all arguments
    XS_ARGS=(${XS_PARAMS[@]})

    # Check for joint short flags and expand them
    for arg in "${XS_PARAMS[@]}"; do
        # Check if the argument is a joint short flag (e.g., -abc)
        if [[ "$arg" =~ ^-[a-zA-Z]{2,}$ ]]; then
            handle_joint_short_flags "${arg:1}"  # Call the function to handle the joint short flags
            unset XS_PARAMS[$arg]  # Remove the joint short flag from the XS_PARAMS array
        fi
    done

    xs_generate_case "${XS_PARAMS[@]}"

    [ -n "$_XS_ARGS_DEBUG" ] && xs_run_debug "${xRUN_ARGS[@]}";
}
# Validate if $xarg variable contains a value and run the code block
# Usage: xcase <value> <code_block>
xcase(){
    xs_func ifname
    xs_debug "${REVERSE} ${BASH_SOURCE[1]} - call of $(ifname)() '$*' ${RESET}\n"
    local value="$1"; shift
    local code_block="$@"
    if [[ "$xarg" =~ $value ]]; then
        eval "$code_block"
    fi
}

# internal helper function to set default values
# Usage: .xs <argument>
# `-> argument can be:
#   --init: initialize script variables
#   --require-value <value> <var_name>: require a value for a variable
#   --require-one <args>: require at least one argument
#   --hl <char>: prints a horizontal line with the given character
.xs(){

    case "${1}" in
        --init)
            shift;
            xs_version; xs_created; xs_updated; xs_author_name; xs_author_mail
        ;;
        --require-value)
            shift;
            test -z "$1" && { xs_usage --field-error "$2"; } 
        ;;
        --require-one)
            shift;
            # no arg given?
            if [ -z "$1" ]; then
                # but stdin is a term (then its a pipe / redirect)
                if [[ ! -t 0 ]]; then
                    # has data to be handled by app/script, so ignore and continue
                    true
                else
                    # raise error
                    xs_usage --missing-param
                fi
            fi
        ;;
        --hl | --horizontal-line)
            shift;
            xs_hl $1
        ;;
    esac
}

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# initialize var 'xarg'
xarg=''

xs_source --local xs_version xs_created xs_updated xs_author_name xs_author_mail xs_hl

# fill vars VERSION, XS_CREATED_AT, XS_AUTHOR_NAME
.xs --init

# define current_cmd at start
xcmd=main
args_hash="${xcmd}-args"
groups_hash="${xcmd}-groups"

# hash to save app params
Hash.new -t "$args_hash"
Hash.new -t "$groups_hash"

# Hash.put "$args_hash" "$param_id" "$param_text";;

block=''
