#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: colors
# Created: Sunday, 2023/02/05 - 22:36:36
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2026/08/27 - 14:50:51
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.7.199
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > xshell colors library
# ############################################################################
# HISTORY:
#

_xLIB_COLORS_=true

# shellcheck disable=SC2034
# `-> ignore alert about declared variables but not used

# setup colors (define variables)
xs_enable_colors(){
  # Reset all attributes
  RESET='\033[0m'

  # Style attributes
  BOLD='\033[1m'
  DIM='\033[2m'
  ITALIC='\033[3m'
  UNDERLINED='\033[4m'
  BLINK='\033[5m'
  REVERSE='\033[7m'
  HIDDEN='\033[8m'

  # Foreground colors
  BLACK='\033[30m'
  RED='\033[31m'
  GREEN='\033[32m'
  YELLOW='\033[33m'
  BLUE='\033[34m'
  MAGENTA='\033[35m'
  CYAN='\033[36m'
  WHITE='\033[37m'
  GREY='\033[90m'

  # Foreground bright colors
  BLACK_BRIGTH='\033[30m'
  RED_BRIGTH='\033[31m'
  GREEN_BRIGTH='\033[32m'
  YELLOW_BRIGTH='\033[33m'
  BLUE_BRIGTH='\033[34m'
  MAGENTA_BRIGTH='\033[35m'
  CYAN_BRIGTH='\033[36m'
  WHITE_BRIGTH='\033[37m'
  GREY_BRIGTH='\033[90m'

  # Background colors
  BGBLACK='\033[40m'
  BGRED='\033[41m'
  BGGREEN='\033[42m'
  BGYELLOW='\033[43m'
  BGBLUE='\033[44m'
  BGMAGENTA='\033[45m'
  BGCYAN='\033[46m'
  BGWHITE='\033[47m' 
  BGGREY='\033[100m'

  # Background bright colors
  BGBLACK_BRIGTH='\033[40m'
  BGRED_BRIGTH='\033[41m'
  BGGREEN_BRIGTH='\033[42m'
  BGYELLOW_BRIGTH='\033[43m'
  BGBLUE_BRIGTH='\033[44m'
  BGMAGENTA_BRIGTH='\033[45m'
  BGCYAN_BRIGTH='\033[46m'
  BGWHITE_BRIGTH='\033[47m'
  BGGREY_BRIGTH='\033[100m'  

  # create ALIASES for all attributes and colors
  ATTR_BOLD=${BOLD}
  ATTR_DIM=${DIM}
  ATTR_ITALIC=${ITALIC}
  ATTR_UNDERLINED=${UNDERLINED}
  ATTR_BLINK=${BLINK}
  ATTR_REVERSE=${REVERSE}
  ATTR_HIDDEN=${HIDDEN}

  FG_BLACK=${BLACK}
  FG_RED=${RED}
  FG_GREEN=${GREEN}
  FG_YELLOW=${YELLOW}
  FG_BLUE=${BLUE}
  FG_MAGENTA=${MAGENTA}
  FG_CYAN=${CYAN}
  FG_WHITE=${WHITE}
  FG_GREY=${GREY}

  FG_BLACK_BRIGTH=${BLACK_BRIGTH}
  FG_RED_BRIGTH=${RED_BRIGTH}
  FG_GREEN_BRIGTH=${GREEN_BRIGTH}
  FG_YELLOW_BRIGTH=${YELLOW_BRIGTH}
  FG_BLUE_BRIGTH=${BLUE_BRIGTH}
  FG_MAGENTA_BRIGTH=${MAGENTA_BRIGTH}
  FG_CYAN_BRIGTH=${CYAN_BRIGTH}
  FG_WHITE_BRIGTH=${WHITE_BRIGTH}
  FG_GREY_BRIGTH=${GREY_BRIGTH}

  BG_BLACK=${BGBLACK}
  BG_RED=${BGRED}
  BG_GREEN=${BGGREEN}
  BG_YELLOW=${BGYELLOW}
  BG_BLUE=${BGBLUE}
  BG_MAGENTA=${BGMAGENTA}
  BG_CYAN=${BGCYAN}
  BG_WHITE=${BGWHITE}
  BG_GREY=${BGGREY}

  BG_BLACK_BRIGTH=${BGBLACK_BRIGTH}
  BG_RED_BRIGTH=${BGRED_BRIGTH}
  BG_GREEN_BRIGTH=${BGGREEN_BRIGTH}
  BG_YELLOW_BRIGTH=${BGYELLOW_BRIGTH}
  BG_BLUE_BRIGTH=${BGBLUE_BRIGTH}
  BG_MAGENTA_BRIGTH=${BGMAGENTA_BRIGTH}
  BG_CYAN_BRIGTH=${BGCYAN_BRIGTH}
  BG_WHITE_BRIGTH=${BGWHITE_BRIGTH}
  BG_GREY_BRIGTH=${BGGREY_BRIGTH}

  FGBLACK=${BLACK}
  FGRED=${RED}
  FGGREEN=${GREEN}
  FGYELLOW=${YELLOW}
  FGBLUE=${BLUE}
  FGMAGENTA=${MAGENTA}
  FGCYAN=${CYAN}
  FGWHITE=${WHITE}
  FGGREY=${GREY}

# Comparison Summary
# State [[ -z "$var" ]]	[[ -z "${var+x}" ]]	[[ ! -v var ]]
# Unset true	true	true
# Set (empty)	true	false	false
# Set (value)	false	false	false

  # Short semantic aliases: 
  [ -z "$R" ] && R=${RESET}
  
  # attributes
  [ -z "$B" ] && B=${BOLD}
  [ -z "$M" ] && M=${DIM}
  [ -z "$I" ] && I=${ITALIC}
  [ -z "$U" ] && U=${UNDERLINED}
  [ -z "$K" ] && K=${BLINK}
  [ -z "$V" ] && V=${REVERSE}
  [ -z "$H" ] && H=${HIDDEN}

  # Foreground (one-letter)
  [ -z "$k" ] && k=${BLACK}
  [ -z "$r" ] && r=${RED}
  [ -z "$g" ] && g=${GREEN}
  [ -z "$y" ] && y=${YELLOW}
  [ -z "$b" ] && b=${BLUE}
  [ -z "$m" ] && m=${MAGENTA}
  [ -z "$c" ] && c=${CYAN}
  [ -z "$w" ] && w=${WHITE}
  [ -z "$e" ] && e=${GREY}

  # Background (two-letter: 'b'+color)
  [ -z "$bk" ] && bk=${BGBLACK}
  [ -z "$br" ] && br=${BGRED}
  [ -z "$bg" ] && bg=${BGGREEN}
  [ -z "$by" ] && by=${BGYELLOW}
  [ -z "$bb" ] && bb=${BGBLUE}
  [ -z "$bm" ] && bm=${BGMAGENTA}
  [ -z "$bc" ] && bc=${BGCYAN}
  [ -z "$bw" ] && bw=${BGWHITE}
  [ -z "$be" ] && be=${BGGREY}

}

# unset all colors/attributes 
xs_disable_colors(){
  for var in RESET BOLD DIM ITALIC UNDERLINE BLINK REVERSE HIDDEN \
    ATTR_BOLD ATTR_DIM ATTR_ITALIC ATTR_UNDERLINED ATTR_BLINK ATTR_REVERSE ATTR_HIDDEN \
    BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE GREY \
    FGBLACK FGRED FGGREEN FGYELLOW FGBLUE FGMAGENTA FGCYAN FGWHITE FGGREY \
    BLACK_BRIGTH RED_BRIGTH GREEN_BRIGTH YELLOW_BRIGTH BLUE_BRIGTH MAGENTA_BRIGTH CYAN_BRIGTH WHITE_BRIGTH GREY_BRIGTH \
    FG_BLACK_BRIGTH FG_RED_BRIGTH FG_GREEN_BRIGTH FG_YELLOW_BRIGTH FG_BLUE_BRIGTH FG_MAGENTA_BRIGTH FG_CYAN_BRIGTH FG_WHITE_BRIGTH FG_GREY_BRIGTH \
    BGBLACK BGRED BGGREEN BGYELLOW BGBLUE BGMAGENTA BGCYAN BGWHITE BGGREY \
    BG_BLACK BG_RED BG_GREEN BG_YELLOW BG_BLUE BG_MAGENTA BG_CYAN BG_WHITE BG_GREY \
    BG_BLACK_BRIGTH BG_RED_BRIGTH BG_GREEN_BRIGTH BG_YELLOW_BRIGTH BG_BLUE_BRIGTH BG_MAGENTA_BRIGTH BG_CYAN_BRIGTH BG_WHITE_BRIGTH BG_GREY_BRIGTH \
    k r g y b m c w e bk br bg by bb bm bc bw be \
    R B M I U K V H \
  ; do 
    unset $var
  done
}

# print all colors/attributes in this library
xs_show_colors(){
  # xs_func xs_hl
  xs_hl -
  echo -e "\nxSHELL LIB: COLORS LIB - VARIABLES"
  xs_hl -
  echo -e ""
  echo -e "${BOLD}BOLD or ATTR_BOLD or B ${RESET}"
  echo -e "${DIM}DIM or ATTR_DIM or M ${RESET}"
  echo -e "${ITALIC}ITALIC or ATTR_ITALIC or I ${RESET}"
  echo -e "${UNDERLINED}UNDERLINED or ATTR_UNDERLINED or U ${RESET}"
  echo -e "${BLINK}BLINK or ATTR_BLINK or K ${RESET}"
  echo -e "${REVERSE}REVERSE or ATTR_REVERSE or V ${RESET}"
  echo -e "${HIDDEN}HIDDEN or ATTR_HIDDEN or H ${RESET}"
  echo -e ""
  echo -e "${bw}${BLACK}BLACK or FG_BLACK or FGBLACK or k ${RESET}"
  echo -e "${RED}RED or FG_RED or FGRED or r ${RESET}"
  echo -e "${GREEN}GREEN or FG_GREEN or FGGREEN or g ${RESET}"
  echo -e "${YELLOW}YELLOW or FG_YELLOW or FGYELLOW or y ${RESET}"
  echo -e "${BLUE}BLUE or FG_BLUE or FGBLUE or b ${RESET}"
  echo -e "${MAGENTA}MAGENTA or FG_MAGENTA or FGMAGENTA or m ${RESET}"
  echo -e "${CYAN}CYAN or FG_CYAN or FGCYAN or c ${RESET}"
  echo -e "${WHITE}WHITE or FG_WHITE or FGWHITE or w ${RESET}"
  echo -e "${GREY}GREY or FG_GREY or FGGREY or e ${RESET}"
  echo -e ""
  echo -e "${BGBLACK}BG_BLACK or BGBLACK or bk ${RESET}"
  echo -e "${BGRED}BG_RED or BGRED or br ${RESET}"
  echo -e "${BGGREEN}BG_GREEN or BGGREEN or bg ${RESET}"
  echo -e "${BGYELLOW}BG_YELLOW or BGYELLOW or by ${RESET}"
  echo -e "${BGBLUE}BG_BLUE or BGBLUE or bb ${RESET}"
  echo -e "${BGMAGENTA}BG_MAGENTA or BGMAGENTA or bm ${RESET}"
  echo -e "${BGCYAN}BG_CYAN or BGCYAN or bc ${RESET}"
  echo -e "${BGWHITE}${k}BG_WHITE or BGWHITE or bw ${RESET}"
  echo -e "${BGGREY}BG_GREY or BGGREY or be ${RESET}"
  echo -e "${RESET}RESET or R"
  xs_hl -
  echo -e "\nEND"
  xs_hl -
  echo -e ""
  # show new aliases 
  # xs_show_colors_aliases
}

# short aliases for colors
xs_show_colors_aliases(){
  echo -e "------- ALIASES ------- "
  echo -e "${bw}${k}\$k alias to BLACK ${RESET}"
  echo -e "${r}\$r alias to RED ${RESET}"
  echo -e "${g}\$g alias to GREEN ${RESET}"
  echo -e "${y}\$y alias to YELLOW ${RESET}"
  echo -e "${b}\$b alias to BLUE ${RESET}"
  echo -e "${m}\$m alias to MAGENTA ${RESET}"
  echo -e "${c}\$c alias to CYAN ${RESET}"
  echo -e "${w}\$w alias to WHITE ${RESET}"
  echo -e "${e}\$e alias to GREY ${RESET}"
  echo -e ""
  echo -e "${bk}\$bk alias to BG_BLACK ${RESET}"
  echo -e "${br}\$br alias to BG_RED ${RESET}"
  echo -e "${bg}\$bg alias to BG_GREEN ${RESET}"
  echo -e "${by}\$by alias to BG_YELLOW ${RESET}"
  echo -e "${bb}\$bb alias to BG_BLUE ${RESET}"
  echo -e "${bm}\$bm alias to BG_MAGENTA ${RESET}"
  echo -e "${bc}\$bc alias to BG_CYAN ${RESET}"
  echo -e "${bw}${k}\$bw alias to BG_WHITE ${RESET}"
  echo -e "${be}\$be alias to BG_GREY ${RESET}"
  echo -e "------- END ------- "
}

# enable colors by default (when this file/library is loaded)
xs_enable_colors