#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: colors
# Created: Sunday, 2023/02/05 - 22:36:36
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2026/08/25 - 19:36:52
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 1.0.5.124
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  > xshell colors library
# ############################################################################
# HISTORY:
#

_xLIB_COLORS_=true

# shellcheck disable=SC2034
# `-> ignore alert about declared variables but not used

# setup colors (define variables)
xs_enable_colors(){
  # Reset all attributes
  RESET='\033[0m'

  # Style attributes
  BOLD='\033[1m'
  DIM='\033[2m'
  ITALIC='\033[3m'
  UNDERLINED='\033[4m'
  BLINK='\033[5m'
  REVERSE='\033[7m'
  HIDDEN='\033[8m'

  # Foreground colors
  BLACK='\033[30m'
  RED='\033[31m'
  GREEN='\033[32m'
  YELLOW='\033[33m'
  BLUE='\033[34m'
  MAGENTA='\033[35m'
  CYAN='\033[36m'
  WHITE='\033[37m'
  GREY='\033[90m'

  # Foreground bright colors
  BLACK_BRIGTH='\033[30m'
  RED_BRIGTH='\033[31m'
  GREEN_BRIGTH='\033[32m'
  YELLOW_BRIGTH='\033[33m'
  BLUE_BRIGTH='\033[34m'
  MAGENTA_BRIGTH='\033[35m'
  CYAN_BRIGTH='\033[36m'
  WHITE_BRIGTH='\033[37m'
  GREY_BRIGTH='\033[90m'

  # Background colors
  BGBLACK='\033[40m'
  BGRED='\033[41m'
  BGGREEN='\033[42m'
  BGYELLOW='\033[43m'
  BGBLUE='\033[44m'
  BGMAGENTA='\033[45m'
  BGCYAN='\033[46m'
  BGWHITE='\033[47m' 
  BGGREY='\033[100m'

  # Background bright colors
  BGBLACK_BRIGTH='\033[40m'
  BGRED_BRIGTH='\033[41m'
  BGGREEN_BRIGTH='\033[42m'
  BGYELLOW_BRIGTH='\033[43m'
  BGBLUE_BRIGTH='\033[44m'
  BGMAGENTA_BRIGTH='\033[45m'
  BGCYAN_BRIGTH='\033[46m'
  BGWHITE_BRIGTH='\033[47m'
  BGGREY_BRIGTH='\033[100m'  

  # create ALIASES for all attributes and colors
  ATTR_BOLD=${BOLD}
  ATTR_DIM=${DIM}
  ATTR_ITALIC=${ITALIC}
  ATTR_UNDERLINED=${UNDERLINED}
  ATTR_BLINK=${BLINK}
  ATTR_REVERSE=${REVERSE}
  ATTR_HIDDEN=${HIDDEN}

  FG_BLACK=${BLACK}
  FG_RED=${RED}
  FG_GREEN=${GREEN}
  FG_YELLOW=${YELLOW}
  FG_BLUE=${BLUE}
  FG_MAGENTA=${MAGENTA}
  FG_CYAN=${CYAN}
  FG_WHITE=${WHITE}
  FG_GREY=${GREY}

  FG_BLACK_BRIGTH=${BLACK_BRIGTH}
  FG_RED_BRIGTH=${RED_BRIGTH}
  FG_GREEN_BRIGTH=${GREEN_BRIGTH}
  FG_YELLOW_BRIGTH=${YELLOW_BRIGTH}
  FG_BLUE_BRIGTH=${BLUE_BRIGTH}
  FG_MAGENTA_BRIGTH=${MAGENTA_BRIGTH}
  FG_CYAN_BRIGTH=${CYAN_BRIGTH}
  FG_WHITE_BRIGTH=${WHITE_BRIGTH}
  FG_GREY_BRIGTH=${GREY_BRIGTH}

  BG_BLACK=${BGBLACK}
  BG_RED=${BGRED}
  BG_GREEN=${BGGREEN}
  BG_YELLOW=${BGYELLOW}
  BG_BLUE=${BGBLUE}
  BG_MAGENTA=${BGMAGENTA}
  BG_CYAN=${BGCYAN}
  BG_WHITE=${BGWHITE}
  BG_GREY=${BGGREY}

  BG_BLACK_BRIGTH=${BGBLACK_BRIGTH}
  BG_RED_BRIGTH=${BGRED_BRIGTH}
  BG_GREEN_BRIGTH=${BGGREEN_BRIGTH}
  BG_YELLOW_BRIGTH=${BGYELLOW_BRIGTH}
  BG_BLUE_BRIGTH=${BGBLUE_BRIGTH}
  BG_MAGENTA_BRIGTH=${BGMAGENTA_BRIGTH}
  BG_CYAN_BRIGTH=${BGCYAN_BRIGTH}
  BG_WHITE_BRIGTH=${BGWHITE_BRIGTH}
  BG_GREY_BRIGTH=${BGGREY_BRIGTH}

  FGBLACK=${BLACK}
  FGRED=${RED}
  FGGREEN=${GREEN}
  FGYELLOW=${YELLOW}
  FGBLUE=${BLUE}
  FGMAGENTA=${MAGENTA}
  FGCYAN=${CYAN}
  FGWHITE=${WHITE}
  FGGREY=${GREY}

  # Short semantic aliases: fg one-letter, bg two-letter ('b'+color)
  # Foreground (one-letter)
  k=${BLACK}
  r=${RED}
  g=${GREEN}
  y=${YELLOW}
  b=${BLUE}
  m=${MAGENTA}
  c=${CYAN}
  w=${WHITE}
  e=${GREY}

  # Background (two-letter: 'b'+color)
  bk=${BGBLACK}
  br=${BGRED}
  bg=${BGGREEN}
  by=${BGYELLOW}
  bb=${BGBLUE}
  bm=${BGMAGENTA}
  bc=${BGCYAN}
  bw=${BGWHITE}
  be=${BGGREY}

}

# unset all colors/attributes 
xs_disable_colors(){
  for var in RESET BOLD DIM ITALIC UNDERLINE BLINK REVERSE HIDDEN \
    ATTR_BOLD ATTR_DIM ATTR_ITALIC ATTR_UNDERLINED ATTR_BLINK ATTR_REVERSE ATTR_HIDDEN \
    BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE GREY \
    FGBLACK FGRED FGGREEN FGYELLOW FGBLUE FGMAGENTA FGCYAN FGWHITE FGGREY \
    BLACK_BRIGTH RED_BRIGTH GREEN_BRIGTH YELLOW_BRIGTH BLUE_BRIGTH MAGENTA_BRIGTH CYAN_BRIGTH WHITE_BRIGTH GREY_BRIGTH \
    FG_BLACK_BRIGTH FG_RED_BRIGTH FG_GREEN_BRIGTH FG_YELLOW_BRIGTH FG_BLUE_BRIGTH FG_MAGENTA_BRIGTH FG_CYAN_BRIGTH FG_WHITE_BRIGTH FG_GREY_BRIGTH \
    BGBLACK BGRED BGGREEN BGYELLOW BGBLUE BGMAGENTA BGCYAN BGWHITE BGGREY \
    BG_BLACK BG_RED BG_GREEN BG_YELLOW BG_BLUE BG_MAGENTA BG_CYAN BG_WHITE BG_GREY \
    BG_BLACK_BRIGTH BG_RED_BRIGTH BG_GREEN_BRIGTH BG_YELLOW_BRIGTH BG_BLUE_BRIGTH BG_MAGENTA_BRIGTH BG_CYAN_BRIGTH BG_WHITE_BRIGTH BG_GREY_BRIGTH \
  ; do 
    unset $var
  done
}

# print all colors/attributes in this library
xs_show_colors(){
  echo -e "${BOLD}BOLD${RESET}"
  echo -e "${DIM}DIM${RESET}"
  echo -e "${ITALIC}ITALIC${RESET}"
  echo -e "${UNDERLINED}UNDERLINED${RESET}"
  echo -e "${BLINK}BLINK${RESET}"
  echo -e "${REVERSE}REVERSE${RESET}"
  echo -e "${HIDDEN}HIDDEN${RESET}"
  echo -e ""
  echo -e "${BLACK}BLACK${RESET}"
  echo -e "${RED}RED${RESET}"
  echo -e "${GREEN}GREEN${RESET}"
  echo -e "${YELLOW}YELLOW${RESET}"
  echo -e "${BLUE}BLUE${RESET}"
  echo -e "${MAGENTA}MAGENTA${RESET}"
  echo -e "${CYAN}CYAN${RESET}"
  echo -e "${WHITE}WHITE${RESET}"
  echo -e "${GREY}GREY${RESET}"
  echo -e ""
  echo -e "${BGBLACK}BGBLACK${RESET}"
  echo -e "${BGRED}BGRED${RESET}"
  echo -e "${BGGREEN}BGGREEN${RESET}"
  echo -e "${BGYELLOW}BGYELLOW${RESET}"
  echo -e "${BGBLUE}BGBLUE${RESET}"
  echo -e "${BGMAGENTA}BGMAGENTA${RESET}"
  echo -e "${BGCYAN}BGCYAN${RESET}"
  echo -e "${BGWHITE}BGWHITE${RESET}"
  echo -e "${BGGREY}BGGREY${RESET}"
}

# enable colors by default (when this file/library is loaded)
xs_enable_colors