#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: init
# Created: Thursday, 2021/05/20 - 13:18:34
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/08/10 - 08:08:55
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.23.898
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# shellcheck disable=SC1090,SC1091,SC2154,SC2034
  # `-> SC1090 - Can't follow non-constant source: Use a directive to specify location.
  # `-> SC1091 - Not following: (error message here)
  # `-> SC2154 - var is referenced but not assigned: (install script set it on user/system env)
  # `-> SC2034 - foo appears unused. Verify it or export it: (Some vars are defined to be used by other scripts )
  
#  autoload 'colors' if in DEBUG mode
[ -n "$_INIT_DEBUG_" ] && source "$xSHELL_PATH/colors"   

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
APP=$(basename "$0")          # application name
APP_NAME=$APP                 # application name
APP_PATH=$0                   # application path and name
APP_DIR=$(dirname "$0")       # application current directory
APP_HOME="$HOME/.xshell/$APP" # application home (store data)
APP_DATA=$APP_HOME
# DEPRECATED: $APP_DIR will become $APP_HOME and $APP_HOME turn to $APP_DATA

# store current app requirements (binaries)
_REQUIREMENTS_=''
_MISSING_REQUIREMENTS_=''

# store loaded LIBs
xSHELL_LIBS=()

# PATHs to search a LIB
xSHELL_DIRS=( 
  "$APP_DIR/" 
  "$APP_DIR/lib/"
  "$APP_DIR/lib/functions/"
  "$APP_DIR/vendor/"
  "$xSHELL_PATH/"
  "$xSHELL_PATH/lib/" 
  "$xSHELL_PATH/lib/functions/"
  "$xSHELL_PATH/vendor/"
)

# def set_assoc_array(key, value): function to set a value in a simulated associative array
# ex:
# set_assoc_array "lib1" "/path/to/lib1"
# set_assoc_array "lib2" "/path/to/lib2"
set_assoc_array() {
    local key=$1
    local value=$2
    eval "_xLIB_DIRS_${key}=\"${value}\""
}

# def get_assoc_array(key): function to get a value from a simulated associative array
# Ex:
# echo "lib1: $(get_assoc_array lib1)"
# echo "lib2: $(get_assoc_array lib2)"

get_assoc_array() {
    local key=$1
    eval "echo \$_xLIB_DIRS_${key}"
}

# def to_uppercase(string): function to convert a string to uppercase
to_uppercase() {
    echo "$1" | tr '[:lower:]' '[:upper:]'
}

# declare -A _xLIB_DIRS_
_CALLER_=''
_USE_COUNT_=0
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# def xsetHome(subdirs): function to create default $APP_DATA and subfolders
# ex: setHome {dir1, dir2}
xsetHome(){
  APP_DATA=$HOME/.xshell/$APP
  APP_HOME=$APP_DATA
  mkdir -p "$APP_DATA/$*"
}

# def use(lib1, lib2, ...): function to import/use some library
# ex: use args utils mycustomlib
use(){
  local lib_file lib dir
  
  ((_USE_COUNT_+=1))  # Increment the use counter
  
  # function to check if some lib already loaded (search for a const var _xLIB_NAME_)
  checkLibLoaded(){
    local lib_const
    
    # local lib_const=${1^^}          # convert fist arg to UPCASE 
    lib_const=$(to_uppercase "$1")  # Convert the argument to uppercase
    lib_const=${lib_const//./_}     # replace '.' for '_'
    lib_const=${lib_const//LIB/}    # remove word 'lib' from filename 
    lib_const="_xLIB_${lib_const}"  # Const for mark lib as loaded

    # check last char (needs to be equal '_' underline) 
    [ ! "${lib_const:-1}" == "_" ]  && lib_const+="_"  # Add an underscore if it's not already there

    # check if load lib has a defined var _xLIB_NAME_ and its not null
    if eval "[ -z \"\$${lib_const}\" ]" ; then
      [ "$_INIT_DEBUG_" == 'true' ] && { 
        echo -e "${RED}\`-> lib '${1}' not loaded. (const "\
          "'${BGRED}${BLACK}$lib_const${RESET}${RED}' not found)${RESET}"  # Print an error message if the library is not loaded
      }
      return 1
    else
      [ "$_INIT_DEBUG_" == 'true' ] && {
        echo -e "${YELLOW}\`-> skipping '${1}' -> Lib already loaded. (const '${BGYELLOW}${BLACK}$lib_const${RESET}${YELLOW}' found)${RESET}"  # Print a message if the library is already loaded
      }
      return 0
    fi
  }

  # trackback function caller
  if [ "$_USE_COUNT_" -eq 1 ]; then 
    _CALLER_="$0" ; _LIB_=$1  # Set the caller and library variables
  else
    [ "$_CALLER_" == "$_LIB_" ] && { 
      _CALLER_="$0";
    } || _CALLER_=$_LIB_  # Update the caller and library variables if necessary
  fi
  
  [ "$_INIT_DEBUG_" == 'true' ] && \
    echo -e "call ${YELLOW}'use ${MAGENTA}$*${RESET}' from ${CYAN}'$_CALLER_'${RESET}"  # Print a message indicating that the use function is being called
  
  for lib_file in "$@"; do
    
    if ! checkLibLoaded "$lib_file"; then

      # shellcheck disable=SC2155         # warning - declare and assign separate
      # local current_path=$(dirname "$0")  # Get the directory path of the current script
      # Novo array para armazenar os paths com o arquivo adicionado
      lib_dirs=()
      

      # Iterar sobre cada item do array original
      for dir in "${xSHELL_DIRS[@]}"; do
        # Adicionar o nome do arquivo ao final do path
        lib_dirs+=("$dir$lib_file")
      done

      local included=''
      
      # search file in default destinations
      local li=0
      for lib in "${lib_dirs[@]}"; do

        if source "${lib}" 2> /dev/null ; then
          xSHELL_LIBS+=($lib)
          _CALLER_=${lib}
          # success? set a flag; break loop
          [ "$_INIT_DEBUG_" == 'true' ] && { 
            # printf "     %-${max_length}s   %s\n" "$key" "$desc"
            
            # printf "   %s\`-> loading '%s' %-25s - directory: %s/%s"  "${GREEN}" "${xSHELL_DIRS[$li]}" "${RESET}" "${CYAN}" "$((li+1))" "${#xSHELL_DIRS[@]}${RESET}"
            
            echo -e "${GREEN}  \`-> loading '${lib}'${RESET} - "\
              "${CYAN}directory: $((li+1))/${#xSHELL_DIRS[@]}${RESET})"
          }
          included="true"
          
          # _xLIB_DIRS_[$lib_file]="${lib}"
          set_assoc_array "${lib_file//./_}" "$lib"

          break
        fi
        li=$((li+1))
      done
    else 
      included="true"
    fi

    # not included with success? raise a error 
    test -z "$included" && { 
      echo -e "\n${RED}Error importing lib '$lib_file' - NOT_FOUND!${RESET}"
      [ "$_INIT_DEBUG_" == 'true' ] && { 
          local all_dirs=${xSHELL_DIRS[*]}
          echo -e "${RED} \`-> searched on dir's:\n   *"\
            "${all_dirs// /\\n   \* }"\
            "${RESET}"
        }
      exit 1
    }
  
  done
  _USE_COUNT_=0
}

# create some aliases for use/import libraries
alias include=use
alias import=use
alias require=use
alias load=use
alias unit=use
alias xuse=use

# def xrequirements(bin1, bin2, "bin3A|bin3B"): function to validate required binaries (bin1, bin2, "bin3A|bin3B")
# ex: xrequirements bin1 bin2 "bin3A|bin3B"
xrequirements(){
  local missing=""
  local found=''
  
  # def falil(tools): function to print a error message
  # ex: fail "bin1"
  fail(){
    local tools=$@
    local error_msg="requirements error! please install missing tools: '${tools//\|/' or '}'"
    echo -e "$error_msg"
    if source "$xSHELL_PATH/system" 2> /dev/null; then
      xsys.notify "$APP" "$error_msg"
    fi
  }
  
  # def check(tool): verify if a package exists on the system
  # ex: check mkdir
  check(){ which "$1" &> /dev/null; }
  
  _REQUIREMENTS_=$*

  # iterate over each tool provided as an argument
  for tool in $_REQUIREMENTS_; do
    # check if the current tool contains a pipe character (indicating alternatives binaries - bin1|bin2)
    if [[ "$tool" =~ "|" ]]; then
      # iterate over each alternative binary in the list (ex: bin1|bin2)
      for t in ${tool//\|/ }; do 
        # check each alternative binary in the list (ex: bin1)
        if check "$t"; then
          # if the binary is found, set the 'found' flag to true and break the loop
          found=true
          break;
        else
          # if the binary is not found, set the 'found' flag to false and add it to the 'missing' list
          found=false
          [ -z "$_MISSING_REQUIREMENTS_" ] && _MISSING_REQUIREMENTS_+="$tool" || _MISSING_REQUIREMENTS_+=" $tool"
        fi
      done
      [ "$found" != 'true' ] && { fail "$tool"; source "$xSHELL_PATH/functions/xs_requirements_report"; xs_requirements_report "$_MISSING_REQUIREMENTS_"; exit 10; }
    else
      # Simple binary (not bin1|bin2) - check if the tool is available on the system
      if ! check "$tool"; then
        # if the binary is not found, set the 'found' flag to false and add it to the 'missing' list
        [ -z "$_MISSING_REQUIREMENTS_" ] && _MISSING_REQUIREMENTS_+="$tool" || _MISSING_REQUIREMENTS_+=" $tool"
        found=false
      else 
        # if the binary is found, set the 'found' flag to true
        found=true
      fi
    fi
  done

  #  
  [ -n "$_MISSING_REQUIREMENTS_" ] && { fail "$_MISSING_REQUIREMENTS_"; source "$xSHELL_PATH/functions/xs_requirements_report"; xs_requirements_report "$_MISSING_REQUIREMENTS_"; exit 10; }
}
