#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: init
# Created: Thursday, 2021/05/20 - 13:18:34
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2023/02/13 - 00:42:22
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.13.352
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# shellcheck disable=SC1090,2155

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# debug var
# _INIT_DEBUG_=false      # set to true if false

#  autoload 'colors' if in DEBUG mode
[ "$_INIT_DEBUG_" == 'true' ] && source ~/bin/xSHELL/colors

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
APP=$(basename "$0")      # application name
APP_DIR=$(dirname "$0")   # application current directory
APP_HOME=""               # application home (store data)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~

# function to set $APP_HOME
# ex: setHome {dir1, dir2}
xsetHome(){
  APP_HOME=~/.fbnmtz/$APP
  mkdir -p "$APP_HOME"/"$*"
}

# import/use some library
# ex: use args utils mycustomlib
use(){
  # check if some lib already loaded
  checkLibLoaded(){
    # convert fist arg to UPCASE 
    local name=${1^^}

    # replace '.' for '_'
    name=${name//./_}
    
    # remove word 'lib' from filename (# name=$(sed "s/LIB//" <<< $name))
    name=${name//LIB/}
    
    # Const for mark lib as loaded
    lib_const="_xLIB_${name}"

    # check last char (needs to be equal '_' underline)
    if [[ ! "${lib_const:(-1)}" == "_" ]]; then
      lib_const+="_"
    fi

    # check if load lib has a defined var __LIB_NAME and its not null
    if eval "test -z \"\$${lib_const}\"" ; then
      [ "$_INIT_DEBUG_" == 'true' ] && { 
        echo -e "${RED}\`-> lib '${1}' not loaded. (const '${BGRED}${BLACK}$lib_const${RESET}${RED}' not found.)${RESET}"
      }
      return 1
    else
      [ "$_INIT_DEBUG_" == 'true' ] && echo -e "${YELLOW}\`-> lib '${1}' already loaded (skipping)${RESET}"
      return 0
    fi
  }

  [ "$_INIT_DEBUG_" == 'true' ] && \
    echo -e "call ${YELLOW}'use ${MAGENTA}$*${RESET}' from ${CYAN}'$0'${RESET}"
  
  for lib_file in "$@"; do
    
    if ! checkLibLoaded "$lib_file"; then

      local current_path=$(dirname "$0") 
      local locations=( 
        # search libs on path of current script
        "$current_path/$lib_file" 
        "$current_path/lib/$lib_file" 
        #  search on xSHELL directory 
        "$HOME/bin/xSHELL/$lib_file"
        # tyr to load third party libraries  
        "$HOME/bin/xSHELL/vendor/$lib_file" 
        "$HOME/bin/vendor/$lib_file" 
      )
      local included=''

      # search file in default destinations
      li=0
      for lib in "${locations[@]}"; do

        if source "$lib" 2> /dev/null ; then
          # success? set a flag; break loop
          [ "$_INIT_DEBUG_" == 'true' ] && { 
            echo -en "${GREEN}  \`-> loaded '${locations[$li]}'${RESET} - " 
            echo -e  "${CYAN}location: $((li+1))/${#locations[@]}${RESET})"
          }
          included="true"
          break
        fi
        li=$((li+1))
      done
    else 
      included="true"
    fi

    # not included with success? raise a error 
    test -z "$included" && { echo "${RED}Error importing lib: $lib_file${RESET}"; exit 1; }
  
  done
}

# create some aliases for use/import libraries
alias include=use
alias import=use
alias require=use
alias load=use
alias unit=use

# validade requirements
# ex: xrequirements bin1 bin2 bin3A:bin3B
xrequirements(){
  fail(){
    local tool=$1
    local error_msg="requirements error! please search and install a package with missing tool: '${tool//\:/\' or \'}' ."
    echo -e "$error_msg"
    alert "$0" "$error_msg"
    exit 10
  }
  # check if a package exists on the system
  # ex; check bin1
  check(){
    which "$1" &> /dev/null
  }
  for tool in "$@"; do
    if [[ "$tool" =~ ":" ]]; then
      local found=''
      for t in ${tool//\:/ }; do 
        if check "$t"; then
          found=true
          break;
        else
          found=false
        fi
      done
      [ "$found" != 'true' ] && fail "$tool"
    else
      if ! check "$tool"; then
        fail "$tool"
      fi
    fi
  done
}
