#!/usr/bin/env bash
#
# ############################################################################
# Project: xshell (none)
# File...: xSHELL.load
# Created: Saturday, 2023/01/14 - 17:11:24
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2023/01/14 - 18:36:33
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.1.81
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
APP_DIR=$(dirname "$0")

[ "$1" == "--xdebug" ] && xDEBUG=true

{ test -d "$APP_DIR"/xSHELL && debug_information='source "./xSHELL/lib/init"'; source "./xSHELL/lib/init" || debug_information+=" fail load init lib" ; } || \
{ test -d "$APP_DIR"/lib    && debug_information='source "./lib/init"';        source "./lib/init"        || debug_information+=" fail load init lib" ; } || \
{ test -d ~/bin/lib         && debug_information='source "./~/bin/lib"';       source "./~/bin/lib"       || debug_information+=" fail load init lib" ; } 

[ -n "$xDEBUG" ] && echo "$debug_information"