#!/usr/bin/env bash
#
# ############################################################################
# Project: xshell (none)
# File...: initialize
# Created: Saturday, 2023/01/14 - 17:11:24
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/01/15 - 14:12:03
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.2.120
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
APP_DIR="$(dirname \"$0\")"

directories=("$APP_DIR/xSHELL/lib" "$APP_DIR/lib" "~/bin/lib")

for dir in "${directories[@]}" ; do 
    if [ -d "${dir}" ]; then
        debug_information="source \"${dir}\""
        if source "${dir}"; then
            break
        fi
    fi
done

# show debug information?
[ -n "$xDEBUG" ] && echo "$debug_information"