#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: install-xshell
# Created: Friday, 2023/01/06 - 23:38:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/01/15 - 14:43:14
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.6.55
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

source ~/bin/lib/init
use exceptions

github=https://github.com
repo=fbnmtz/xSHELL

if [ -d ~/bin ] || [ -L ~bin ]; then
    echo "Error: $ExDirAlredyExists! faild to install repository '$repo'. Dir '~/bin' already exists"
    exit $ExDirAlredyExists
else
    # clone this repo to your '/home'
    git clone "${github}/${repo}" ~/bin/xSHELL && \
    
    # Add scripts to your system $PATH
    echo "export PATH=\"\$PATH:\$HOME/bin/xSHELL\"" >> ~/.profile
fi
