#!/usr/bin/env bash
#
# ############################################################################
# Project: shell (none)
# File...: install-shell
# Created: Friday, 2023/01/06 - 23:38:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2023/01/10 - 01:45:25
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.5.48
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

source ~/bin/lib/init
use exceptions

github=https://github.com
repo=fbnmtz/shell

if [ -d ~/bin ]; then
    echo "Error: $ExDirAlredyExists! faild to install repository '$repo'. Dir '~/bin' already exists"
    exit $ExDirAlredyExists
else
    # clone this repo to your '/home'
    git clone "${github}/${repo}" ~/bin && \
    mv ~/bin/scripts/* ~/bin/ && \
    rm -rf ~/bin/scripts
    
    # Add scripts to your system $PATH
    echo "export PATH=\"\$PATH:\$HOME/bin\"" >> ~/.profile
fi