#!/usr/bin/env bash
#
# ############################################################################
# Project: shell (none)
# File...: install-shell
# Created: Friday, 2023/01/06 - 23:38:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2023/01/07 - 08:55:13
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.2.34
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

source ~/bin/lib/init
use exceptions

github=https://github.com
repo=fbnmtz/shell

if [ -d ~/bin ]; then
    echo "faild to install repository '$repo'. Dir already exists"
    exit $exDirAlredyExists
else
    # clone this repo to your '/home'
    git clone "${github}/${repo}" ~/bin
    
    # Add scripts to your system $PATH
    echo "export PATH=\"\$PATH:\$HOME/bin\"" >> ~/.profile
fi