#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: install
# Created: Friday, 2023/01/06 - 23:38:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2024/12/08 - 04:14:24
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.9.197
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# function to require ROOT user
requireROOT(){
    if [ $UID -eq 0 ] ; then 
        return 0 
    else
        echo "Error! You need to be ROOT to install xSHELL"
        exit 1
    fi
}

_sudo(){
    _cmd_=$1
    echo -n "running 'sudo $_cmd_ "; echo
    eval "$_cmd_"
}

url=https://github.com
repo=fbnmtz/xSHELL
default_dir=/opt

echo -n "install xSHELL on directory (default $default_dir): "
read custom_path

if [ -z "${custom_path}" ]; then
    install_dir="$default_dir/xSHELL"
else
    install_dir="${custom_path}/xSHELL"
fi

if [ ! -w "${install_dir}" ]; then
    requireROOT
fi

if [ -d "$install_dir" ] || [ -L "$install_dir" ]; then
    echo "xSHELL is already installed. Do you want to update it? (y/n)"
    read choice
    if [ "${choice^^}" == "Y" ]; then
        cd $install_dir && git pull
    fi
else 
    git clone "${url}/${repo}" "$install_dir" && echo "xSHELL installed."
fi

# Check if the configuration already exists in /etc/profile
if ! grep -q "export _xSHELL_" /etc/profile; then
    # If the configuration does not exist, add it
    _sudo "echo -e '\nexport PATH=\"\$PATH:$install_dir\"' >> /etc/profile"
    _sudo "echo -e '\nexport _xSHELL_=\"${install_dir}\"'  >> /etc/profile"
    echo "Configuration added to /etc/profile"
else
    echo "Configuration already exists in /etc/profile"
fi

# Check if the configuration already exists in /etc/profile
if ! grep -q "export _xSHELL_" /etc/bashrc; then
    # If the configuration does not exist, add it
    _sudo "echo -e '\nexport PATH=\"\$PATH:$install_dir\"' >> /etc/bashrc"
    _sudo "echo -e '\nexport _xSHELL_=\"${install_dir}\"'  >> /etc/bashrc"
    echo "Configuration added to /etc/bashrc"
else
    echo "Configuration already exists in /etc/bashrc"
fi