#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: install
# Created: Friday, 2023/01/06 - 23:38:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2023/01/15 - 15:22:06
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.9.65
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

github=https://github.com
repo=fbnmtz/xSHELL

#local exception
ExDirAlredyExists=10

if [ -d ~/bin/xSHELL ] || [ -L ~/bin/xSHELL ]; then
    echo "Error: $ExDirAlredyExists! faild to install repository '$repo'. Dir '~/bin' already exists"
    exit $ExDirAlredyExists
else
    # clone this repo to your '/home'
    git clone "${github}/${repo}" ~/bin/xSHELL && \
    
    # Add scripts to your system $PATH
    if ! grep "\$PATH:\$HOME/bin/xSHELL" ~/.profile  1> /dev/null  ; then
        echo -e "\nexport PATH=\"\$PATH:\$HOME/bin/xSHELL\"" >> ~/.profile
    fi 
fi
