#!/usr/bin/env bash
#
# ############################################################################
# Project: xshell (none)
# File...: mdisk
# Created: Sunday, 2022/02/27 - 15:31:50
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2023/01/14 - 02:34:40
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.3.162
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
#  > https://www.cyberciti.biz/faq/linux-backup-restore-a-partition-table-with-sfdisk-command/
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source ~/bin/lib/init    
use args 
xrequirements lsblk grep awk aw printf sfdisk smartctl mdate cut rev
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xsetHome
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -l,--list      --var action:list       --desc "list all disks on device"    
xarg --id -m,--mounted   --var action:mounted    --desc "list mounted disks on device"    
xarg --id -u,--unmounted --var action:unmounted  --desc "list unmounted disks on device"    
xarg --id -b,--backup    --var action:bkp,disk+o --desc "backup disk info"    

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xrun --xreject-unknow --xrequire-one --xversionrc "$@"    

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
_mounted(){
    lsblk  -lpn | \
        grep 'part\|crypt\|lvm\|loop\|disk' | \
        awk '$7!="" {printf "%-10s (%6s) - %s\n",  $1, $4, $7}'
}

_unmounted(){
    lsblk  -lpn | \
        grep 'part\|crypt\|lvm\|loop\|disk' | \
        awk '$7=="" {printf "%-10s (%6s)\n", $1, $4 }'
}

_list(){
    lsblk -lpn -o name,type,size | grep disk
}

_preBackup(){
    if [ -n "$disk" ]; then
        filename="$(getFilename $disk -d).sfdisk"
        if doBackup $disk $filename; then
            echo "'$disk' backup done"
        else
            rm "$APP_HOME/$filename"
            echo "disk '$disk' not found"
        fi
    else
        for disk in $(lsblk -lpn -o name,type,size | grep disk | aw 1); do
            disk_name=$(getFilename $disk)
            filename="$(getFilename $disk -d).sfdisk"

            doBackup $disk $filename
            sudo smartctl -i $disk > $APP_HOME/$disk_name.info
            echo "partition table backup: '$disk' done"
        done
    fi
}

doBackup(){
    local disk=$1; 
    local filename=$2
    sfdisk -d $disk 2>/dev/null > "$APP_HOME/$filename"
}

getFilename(){
    [ "$2" == '-d' ] && local suffix="-$(mdate -y -m -d)"
    local disk_name=$(echo $1 | rev | cut -d '/' -f1 | rev)
    echo "${disk_name}${suffix}"
}

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
case "$action" in    
    bkp      ) _preBackup ;;    
    mounted  ) _mounted   ;;
    unmounted) _unmounted ;;
    list     ) _list      ;;
    # restore) sfdisk /dev/sda < /path/to/usb/pen/sda.partition.table.12-30-2015.txt ;;
esac    
    