#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: strings
# Created: Friday, 2021/05/21 - 21:09:41
# Author.: Fabiano Matos, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2024/12/09 - 00:55:10
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.4.91
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

_xLIB_STRINGS_=true

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# import libs/functions
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~

# split a string by a ginver char
# @param $1 - string to be splited
# @param $2 - split in this char (it will be removed)
# @return $array - string splited
strSplit(){
    local array=( $(echo "$1" | tr -s "$2" ' ') )
    echo "${array[@]}"
}

# convert string to a array with each char
strChars(){
    local array=( $(echo "$1" | fold -w1 | tr -s '\n' ' ') )
    echo "${array[@]}"
}

# get SIZE of a str
strLen(){ echo "${#1}"; }
alias strSize=strLen
# echo $1 | wc -m

# reverse a str
strReverse(){ echo "$1" | rev; }

# change case of a string 
upCase(){ echo "$1" | tr a-z A-Z ; }
alias upcase=upCase

lowCase(){ echo "$1" | tr A-Z a-z ; }
alias lowcase=lowCase

# check if a string contains another string
# @param $1: string alvo da busca
# @param $2: texto a ser pesquisado na string
strInclude(){
    local string=$1; reqsubstr=$2;
    if [ -z "${string##*$reqsubstr*}" ]; then 
        echo "true"
        # return 0
    else
        echo "false"
        # return 1
    fi
        
}