#!/usr/bin/env bash
#
# ############################################################################
# Project: shell (none)
# File...: xman
# Created: 2020/02/27 - 00:04:23
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Thursday, 2023/01/05 - 06:54:17
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.5.34
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# load lib (core)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
source ~/bin/lib/init
use args

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
requirements find sed awk sort rofi man llppac

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
APP_HOME=~/.fbnmtz/$APP
mkdir -p $APP_HOME

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xrun --xversionrc "$@"


SELECTED_BIN=$( find /usr/bin/ -type f | \
    sed 's/\/usr\/bin\///g' | \
    awk '{print $1}' | \
    sort | \
    rofi -no-config  \
        -columns 1 \
        -lines 10 \
        -i -dmenu \
        -theme ~/.config/rofi/rofi-menus/themes/appsmenu.rasi \
        -p "Man Search" 
)

# save man content and open 
if [ "$SELECTED_BIN" != "" ]; then
  filename="$APP_HOME/man-$SELECTED_BIN.ps"
  if [ ! -f "$filename" ]; then
    man -t "$SELECTED_BIN" > $filename
  fi
  llppac -t ps $filename
fi