#!/usr/bin/env bash
#
# ############################################################################
# Project: bin (none)
# File...: xSHELL/xshell
# Created: Thursday, 2020/02/18 - 20:44:58
# Author.: @fbnmtz, fgm (devel.fgm@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2023/01/30 - 02:45:19
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.10.199
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090,SC2154
#   * SC1090: Can't follow non-constant source. Use a directive to specify location.
#       -> ignore this warning because shellcheck cant follow or source usage
#   * SC2154: var is referenced but not assigned.
#       -> ignore this warning because shellcheck cant detect variables created by or library system.
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
source ~/bin/xSHELL/init
use args utils xshell.lib

xrequirements touch chmod date

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# set default editor
editor=$(getPath code micro nano vim)
# scripts path
scripts=$HOME/bin
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~

xarg --id -f,--filename  --var name+r         --desc "filename for new script"
xarg --id -l,--lib       --var _xLIB_:true    --desc "define script as a LIB"
xarg --id -H,--header    --var _xHEADER_:true --desc "enable default header on the new script"
xarg --id -e,--editor    --var editor+r       --desc "define editor to open script"

xrun --xreject-unknow --xrequire-one "$@"

if [ -n "$name" ]; then
    filename="$scripts/$name"
fi

# exit if exist a script with this name
if [ -f "$filename" ]; then 
    echo "quiting: script already exists!" 
    exit 1
fi

# open a block and print everything to $filename
{ 
    # add shebang (get by env)
    echo -e "#!/usr/bin/env bash"
    
    # add default header information (if requested) 
    [ "$_xHEADER_" == 'true' ] && templateHeader
    
    # finally, create the new script OR library 
    [ "$_xLIB_" == 'true' ] && templateLib "$name" || templateScript 

} > "$filename"

# set executable permissions
chmod +x "$filename"

# open script on a selected editor (by user with --editor or by function getPath)
$editor "$filename" 
