#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: examples/libs_example
# Created: Thursday, 2023/01/05 - 15:09:19
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/09/21 - 17:47:42
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.7.90
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
# shellcheck disable=SC1090,SC2154    
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
    
# load xshell lib system and use args library
source "$xSHELL_INIT"; xs_use args

# you can list/validade all binaries/tools needed by your script easily using 'requirements' function
xs_require echo

# now, you can easily define args and usage info with 'xarg' function
# params supported:
#      * --id <shortflat,longflag>
#            this param require two params 
#                1. --var or --code
#                2. --desc
#          * --var <var1:varvalue,var2+r,var3+o>
#          * --desc <description>
# We have another param made to be used alone 
#      * --section <group name>
#            this param will group args defined after it

# example: how to set args/actions
xs_arg --section "Custom Args"
xs_arg --id -p,--print   --code "echo 'print test'" --desc "print some code"
xs_arg --id -n,--notify  --var title+r,text+r       --desc "test notify system"
xs_arg --id -m,--math    --var expression+r         --desc "solve math expression" 
xs_arg --id -V,--volume  --var option+r             --desc "volume option (up or down)" 

# after define args, pass all script params (var $@) to 'xrun' function 
# xrun optional params:
#   * --xreject-unknow : throw error when receive an parameter not defined with 'xarg'
#   * --xrequire-one...: throw error if no param given
#   * --xversionrc.....: show full version with release candidate
xs_run --xreject-unknow --xrequire-one --xversionrc "$@"

# code for -m/--math arg
if [ -n "$expression" ] ; then
    echo $(($expression))
fi

# test notification function on lib/system 
if [ -n "$title" ]; then
    xsys.notify "$title" "$text"
fi

# test volume function on lib/system
if [ -n "$option" ]; then
    xsys.vol "--$option"
    xsys.notify Volume "$option" # - $(xsys.vol "--status")"
fi