#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: examples/oarray_example
# Created: Sunday, 2026/09/20 - 01:09:32
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Monday, 2026/09/21 - 19:40:13
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.3.96
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

source "$xSHELL_INIT"
xs_use OArray

# Example usage
arr = new OArray
arr.push "apple"
arr.push "banana"
arr.push "cherry"
arr.push "melon"
arr.add "pineapple"

echo "Array: $(arr.to_s)"
echo "Size.: $(arr.size)"
echo "Count: $(arr.count)"
echo
echo "Is array empty? $(arr.empty)"
echo "Element at index 1: $(arr.at 1)"
echo "Is 'banana' included? $(arr.include "banana")"
echo "Index of 'cherry': $(arr.index_of "cherry")"

# Iterate over the array using string command 
#   `-> change @var_name as you want. Ex @item, @fruit, @value, etc)
#   `-> bellow, each item is available as @var_name.
echo -e "\n.each (simple syntax)"
arr.each "echo item: @var_name"

echo -e "\n.each (block syntax)"
# Iterate over the array using each block
arr.each fruit <<DO
    echo "Fruit: @fruit"
DO

echo -e "\n.each (block syntax with index/value)"
# Iterate over the array using each block with index/value
arr.each i,v <<DO
    echo "Index: @i - Value: @v"
DO

echo

arr.delete_at 1
echo "Array after deleting element at index 1: $(arr.to_s)"

arr.pop
echo "Array after popping last element: $(arr.to_s)"

arr.clear
echo "Array after clearing: $(arr.to_s)"
echo "Is array empty? $(arr.empty)"