#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: examples/oarray_example
# Created: Sunday, 2026/09/20 - 01:09:32
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Tuesday, 2026/09/22 - 12:33:11
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.6.148
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

source "$xSHELL_INIT"
xs_use OArray

# Example usage
arr = new OArray
arr.add "pineapple"
arr.push "banana"
arr.push "cherry"
arr.push "apple"
arr.push "melon"
arr.push "mango"
arr.push "melon"  # Duplicate, should not be added again
arr.push "nuts"

echo "Array: $(arr.to_s)"
echo "Size.: $(arr.size)"
echo "Count: $(arr.count)"
echo
echo "Is array empty? $(arr.empty)"
echo "First element.: $(arr.first)"
echo "Last element..: $(arr.last)"

echo "Element at index 1: $(arr.at 1)"
echo "Is 'banana' included? $(arr.include "banana")"
echo "Index of 'cherry': $(arr.index_of "cherry")"

# Iterate over the array using string command 
#   `-> change @var_name as you want. Ex @item, @fruit, @value, etc)
#   `-> bellow, each item is available as @var_name.
echo -e "\n.each (one string - simple syntax)"
arr.each "echo simple item: @e"

echo -e "\n.each (heredoc block)"
# Iterate over the array using each block
arr.each fruit <<DO
    echo "Fruit: @fruit"
DO

echo -e "\n.each (heredoc block with index/value)"
# Iterate over the array using each block with index/value
arr.each i,v <<DO
    echo "Index: @i - Value: @v"
DO

echo -e "\n.each (two strings - vars and block)"
arr.each i,v 'DO 
    echo "Index: @i - Value: @v"
DONE'

echo

echo "Array as string: $(arr.to_s)"
echo "Sorted (asc).: $(arr.sort asc)"
echo "Sorted (desc): $(arr.sort desc)"
echo "Reversed.....: $(arr.reverse)"
echo "Sum..........: $(arr.sum)"
echo "Unique.......: $(arr.uniq)"

arr.delete_at 1
echo "Array after deleting element at index 1: $(arr.to_s)"

arr.pop
echo "Array after popping last element: $(arr.to_s)"

arr.clear
echo "Array after clearing: $(arr.to_s)"
echo "Is array empty? $(arr.empty)"