#!/usr/bin/env bash
#
# ############################################################################
# Project: xSHELL (none)
# File...: scripts/install
# Created: Friday, 2023/01/06 - 23:38:33
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Sunday, 2026/08/16 - 21:56:33
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.8.642
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description:
#  > install script for xSHELL. Run directly from the repository or download it from the web.
# curl -sSL https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master/scripts/install | bash  -s -- --verbose --dir /custom/path
# bash -s tells bash to read the script from standard input.
# -- is used to separate the script arguments from the bash arguments.
# --verbose and --dir /custom/path are the parameters you want to pass to the script.
# ############################################################################
# HISTORY:
#

if ! type xs_source &> /dev/null; then
  _xs="$xSHELL_PATH/functions/xs_source"
  if [ -f "$_xs" ]; then
    source "$_xs"
  else
    source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master/functions/xs_source)"
  fi
fi

# load additional libraries and functions
xs_source "init echo _sudo append_file check_path require_root upcase" 
xrequirements git tee awk grep dirname curl


# log
if [ "$_VERBOSE_" ]; then
  log() { echo "$@"; }
else
  log() { :; }
fi

# URL and repository information
url=https://github.com
project_name=xSHELL
repo=fbnmtz/$project_name
default_dir=/opt

# simple arguments handle 
[ "$1" == "--verbose" ] && { shift; _VERBOSE_=1; shift; }
[ "$1" == "--dir"     ] && { shift; custom_path=$1; shift; }

echo "$project_name install started..." > $APP_LOG

# verify if stdin is a interactive shell (TTY) 
if [ -t 0 ]; then
    echo "runnung locally (stdin term or redirected from file)."
    # no custom path?
    if [ -z "$custom_path" ]; then
        # Prompt for the install dir
        echo -n "${BLUE}$project_name install${RESET} - Use default location: ($default_dir) or inform new path? (y/n) "
        read -r choice
        if [[ "$(upcase ${choice})" == "Y" ]]; then
            echo -n "inform path to install:"
            read -r custom_path
        fi
    fi
else
    echo "runnung by pipe (ex: curl | bash)."
fi

# Set the installation directory
if [ -z "${custom_path}" ]; then
    # Use the default directory if no custom path is provided
    install_dir="$default_dir/$project_name"  
else
    # Use the custom path if provided
    install_dir="${custom_path}/$project_name"  
fi

_parent_dir=$(dirname "$install_dir")
# Check if the installation directory is writable
if [ -d "$install_dir}" ] && [ ! -w "${install_dir}" ] || [ -d "$_parent_dir" ] && [ ! -w "$_parent_dir" ]; then
    # Require ROOT user if the directory is not writable
    requireROOT "${RED}Error!${RESET} You need to be ROOT to install $project_name in $install_dir"
fi

# Check if it is already installed
if [ -d "$install_dir" ] || [ -L "$install_dir" ]; then
    echo -n "${YELLOW}Warning!${RESET} ${BLUE}$project_name is already installed.${RESET} Do you want to update it? (y/n): "
    read -r choice
    if [ "$(upcase $choice)" == "Y" ]; then  # Check if the user wants to update
        cd "$install_dir" && git pull >> $APP_LOG 2>&1 # Update the repository
    fi
else
    echo -n "clonning repo... "
    git clone "${url}/${repo}" "$install_dir" >> $APP_LOG 2>&1 # Clone the repository if not already installed
    echo "done."
fi

# get user lists
user_list=(awk -F: '($3 >= 1000) && ($1 != "nobody") && ($6 ~ /\/home/) {print $1}' /etc/passwd)

# check if user_list is not empty
if [ ! ${#user_list[@]} -eq 0 ]; then
    # iterate over all
    for user in "${user_list[@]}"; do
        user_file= /home/$user/.xshell_env.sh
        touch $user_file
        $user_file <<< "$(curl -sSL https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master/examples/.xshell_env)"
        echo "export BASH_ENV=~/.xshell_env.sh" | tee -a /home/$user/.profile
        echo "export BASH_ENV=~/.xshell_env.sh" | tee -a /home/$user/.bashrc
        # chmod 644$user_file
        # chmod 644 /home/$user/.profile
        # chmod 644 /home/$user/.bashrc
        chown $user:$user$user_file
        chown $user:$user /home/$user/.profile
        chown $user:$user /home/$user/.bashrc
    done
fi

if is_root; then
    # config files for all system (ROOT)
    touch /etc/profile.d/xshell_env.sh
    /etc/profile.d/xshell_env.sh <<< "$(curl -sSL https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master/examples/.xshell_env)"
    echo "export BASH_ENV=/etc/profile.d/xshell_env.sh" | tee -a /etc/profile
fi

# # files for root (installation wide system)
# root_files=("/etc/profile" "/etc/bashrc" "/etc/bash.bashrc" "/etc/profile.d/$project_name.sh")
# # files for normal users (/home/username/file)
# user_files=(".profile" ".bashrc" ".bash_profile" ".bashAPP_LOGin" ".zshrc" ".zprofile" ".zlogin" ".login")
# # list of users (UID >= 1000 and home directory in /home)
# user_list=(awk -F: '($3 >= 1000) && ($1 != "nobody") && ($6 ~ /\/home/) {print $1}' /etc/passwd)

# # Initialize an empty array to hold the configuration files to be checked and updated
# config_files=() 

# # Check if the script is run as root or not and populate the config_files array accordingly
# if [ $UID -eq 0 ]; then
#     config_files+=("${root_files[@]}")
#     # check if user_list is not empty
#     if [ ! ${#user_list[@]} -eq 0 ]; then
#         # Add user files to config_files for each user in the user_list
#         for user in "${user_list[@]}"; do
#             for file in "${user_files[@]}"; do
#                 user_file="/home/$user/$file"
#                 if [ -f "$user_file" ] && [ -w "$user_file" ]; then
#                     config_files+=("$user_file")
#                 fi
#             done
#         done
#     fi
# else
#     # If not root, only check the current user's files
#     for file in "${user_files[@]}"; do
#         user_file="$HOME/$file"
#         if [ -f "$user_file" ] && [ -w "$user_file" ]; then
#             config_files+=("$user_file")
#         fi
#     done
# fi

# echo "configuring files: ${config_files[@]}... "
# # Loop through each configuration file
# for file in "${config_files[@]}"; do
#     if [ -f "$file" ] && [ -w "$file" ]; then
#         echo "checking $file... "
#         # Check if env vars already exists in the file
#         if ! grep -q "export {$project_name}_PATH" "$file" >> $APP_LOG 2>&1; then
#             echo "Configuring $file... "
#             # If the env var does not exist, add it
#             appendFile "$file" 'export '${project_name}'_PATH="'${install_dir}'"'  
#             appendFile "$file" 'export '${project_name}'_INIT="${'${project_name}'_PATH}/init"'  
#             appendFile "$file" 'export '${project_name}'_BIN="${'${project_name}'_PATH}/bin"'  
#             appendFile "$file" 'export '${project_name}'_SCRIPTS="${'${project_name}'_PATH}/scripts"'  
#             appendFile "$file" 'export '${project_name}'_EXAMPLES="${'${project_name}'_PATH}/examples"'  
#             appendFile "$file" 'export PATH="${PATH}:${'${project_name}'_PATH}:${'${project_name}'_BIN}:${'${project_name}'_SCRIPTS}:${'${project_name}'_EXAMPLES}:${HOME}/bin"' 
#             appendFile "$file" 'xs_init(){ source "${'${project_name}'_PATH}/init" ; }'
#             echo "ENV vars added to $file\n"
#         else
#             echo "\t${YELLOW}Skipping...${RESET} ENV vars already exist in $file"
#         fi
#     else
#         echo "Error! File $file not found or not writable. Please verify."
#         exit 2
#     fi
# done

# echo "configuration done! ${project_name} installed."
