#!/usr/bin/env bash
#
# ############################################################################
# Project: shell (none)
# File...: scripts/xman
# Created: 2020/02/27 - 00:04:23
# Author.: @fbnmtz, fgm (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Wednesday, 2023/01/11 - 20:45:11
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.2.0.61
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# load lib (core)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
source ~/bin/lib/init
use args

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xrequirements find sed awk sort rofi man llppac
xsetHome

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xarg --id -b,--binary --var binary+o --desc "binary to show man"
xrun --xversionrc "$@"
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~

if [ -z $binary ]; then
    SELECTED_BIN=$( find /usr/bin/ /bin/ /sbin/ -type f | \
        sed 's/\/usr\/bin\///g' | \
        sed 's/\/bin\///g' | \
        sed 's/\/sbin\///g' | \
        awk '{print $1}' | \
        sort -u | \
        rofi -no-config  \
            -columns 1 \
            -lines 10 \
            -i -dmenu \
            -p "Man Search" 
    )
else
    SELECTED_BIN=$binary
fi

# save man content and open 
if [ "$SELECTED_BIN" != "" ]; then
  filename="$APP_HOME/man-$SELECTED_BIN.ps"
  if [ ! -f "$filename" ]; then
    man -t "$SELECTED_BIN" > $filename
  fi
  llppac -t ps $filename
fi