#!/usr/bin/env bash
#
# ############################################################################# Project: xSHELL (none)
# File...: scripts/xshell
# Created: Thursday, 2020/02/18 - 20:44:58
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Friday, 2025/02/14 - 01:32:56
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.23.429
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
# shellcheck disable=SC1090,SC2154
#   * SC1090: Can't follow non-constant source. Use a directive to specify location.
#       -> ignore this warning because shellcheck cant follow or source usage
#   * SC2154: var is referenced but not assigned.
#       -> ignore this warning because shellcheck cant detect variables created by or library system.
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~

source "$xSHELL_INIT"

use args utils colors strings xshell.lib
xrequirements touch chmod date

xshell_init

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~
xarg --block "Script's Generation"
# xarg --id -a,--args      --var arguments+r     --desc "define <arguments> for new script"
xarg --id -f,--file      --var name+r          --desc "file <name> for new script"
xarg --id -H,--header    --var _xHEADER_:true  --desc "default HEADER on the new script"
xarg --id -l,--lib       --var _xLIB_:true     --desc "LIB type on new script(can be loaded with 'use' function)"
xarg --id -o,--output    --var dir+r           --desc "output <dir> for new script (default: $DEFAULT_OUTPUT)"
xarg --id -e,--editor    --var editor+r        --desc "<editor> to open new script (default: $editor)"
xarg --id -r,--remove    --var name+r          --desc "remove file <name> (backup: $BACKUP_DIR/<name>)"

xarg --header "xSHELL script generator"

# TODO: planning new features
# xarg --block "xSHELL Packages"
# xarg --id -i,--install   --var package+r        --desc "install a xSHELL <package>"
# xarg --id -r,--remove    --var package+r        --desc "remove a xSHELL <package>"
# xarg --id -s,--search    --var package+r        --desc "search <package> on xSHELL repository"

xrun --xreject-unknow --xrequire-one --xversionrc "$@"

case "${xarg}" in
    r) removeFile "$name" ;;
    *) newFile "$name" ;;
esac